import test from 'node:test';import assert from 'node:assert/strict';
import {bindingFor,validatePlannerSnapshot,validatePlannerPlan,preparedPlannerPlan,buildPlannerPrompt} from '../planner.js';
import {createStorySession} from '../story.js';import {snapshotForFixture,requireLiveFixture} from '../fixtures/prepared.js';
const context={ageBand:'9-11',goals:['authorship'],mentorNotes:'',answerNotes:[]};
function setup(source='A flying whale carries a city.'){const s=createStorySession({initialArtifact:{prepared:true},compile:spec=>({spec})});s.setStory(source);return s;}
function preview(s,ctx=context,origin='imported-proposal'){const request=s.beginPlanner(ctx),plan=preparedPlannerPlan(request);s.previewPlanner(plan,{request,origin});return {request,plan};}
function ack(s){for(const i of s.draft.issues)if(!i.required)s.acknowledge(i.id,true);}
test('strict snapshots reject extras, wrong bounds/type/goals/base state',()=>{for(const mutate of [s=>s.extra='secret',s=>s.generation=-1,s=>s.goals.push('diagnosis'),s=>s.goals.push('authorship'),s=>s.answerNotes=Array(4).fill('x'),s=>s.mentorNotes='x'.repeat(501),s=>s.sourceText='x'.repeat(3001),s=>s.basePrintId=1,s=>s.baseWorld={sky:'dragon'}]){const s=snapshotForFixture('vi-whale');mutate(s);assert.throws(()=>validatePlannerSnapshot(s));}});
test('exact canonical binding includes Unicode, goals, notes and base; key order is stable',()=>{const a=snapshotForFixture('vi-whale'),b=Object.fromEntries(Object.entries(a).reverse());assert.equal(bindingFor(a),bindingFor(b));for(const key of ['sourceText','mentorNotes']){const changed=structuredClone(a);changed[key]+='✨';assert.notEqual(bindingFor(a),bindingFor(changed));}const changed=structuredClone(a);changed.goals=['iteration'];assert.notEqual(bindingFor(a),bindingFor(changed));});
test('prepared proposal derives supported source choices rather than baseline defaults',()=>{const request=snapshotForFixture('en-whale'),p=preparedPlannerPlan(request);assert.equal(p.proposals.whaleColor.value,'teal');assert.equal(p.proposals.cityScale.value,.8);assert.equal(p.proposals.gardens.value,true);assert.equal(p.proposals.starBridge.value,false);for(const field of Object.values(p.proposals))for(const q of field.evidence)assert.equal(request[q.source].slice(q.start,q.end),q.text);});
test('plan validator rejects extras, stale binding, forged quotes/unknown source and unsafe output',()=>{const s=snapshotForFixture('vi-whale');for(const mutate of [p=>p.extra='x',p=>p.inputBinding+='x',p=>p.proposals.sky.value='rainy',p=>p.proposals.sky.evidence[0].text='fake',p=>p.proposals.sky.evidence[0].source='child-secret',p=>p.reflection.en='https://untrusted.invalid',p=>p.title.vi='Em sẽ trở thành kỹ sư',p=>p.reflection.en='alert(1)',p=>p.questions=Array(4).fill({vi:'?',en:'?'}),p=>p.proposals.sky.extra=true]){const p=preparedPlannerPlan(s);mutate(p);assert.throws(()=>validatePlannerPlan(p,s));}});
test('valid literal mentor and answer evidence retain distinct sources, not invented child words',()=>{const s=setup(),ctx={...context,mentorNotes:'Teal is one option.',answerNotes:['A garden?']},{request,plan}=preview(s,ctx);plan.proposals.whaleColor={value:'teal',rationale:{vi:'Gợi ý từ ghi chú người lớn.',en:'Suggestion from the adult note.'},evidence:[{source:'mentorNotes',start:0,end:4,text:'Teal'}]};plan.proposals.gardens={value:true,rationale:{vi:'Một phương án để xem lại.',en:'An option to review.'},evidence:[{source:'answerNote0',start:2,end:8,text:'garden'}]};s.previewPlanner(plan,{request,origin:'imported-proposal'});s.adoptPlanner({locale:'en'});assert.equal(s.canPrint,false);assert.equal(s.draft.fieldEvidence.whaleColor.origin,'imported-proposal');assert.equal(s.draft.fieldEvidence.whaleColor.quotes[0].source,'mentorNotes');s.confirm();s.print();s.requestRevision('night');const q=s.draft.fieldEvidence.whaleColor.quotes[0];assert.equal(q.source,'prior-print');assert.equal(q.sourceField,'mentorNotes');assert.equal(q.text,q.sourceTextSnapshot.slice(q.start,q.end));assert.equal(s.printed.story.plannerSnapshot.mentorNotes,ctx.mentorNotes);});
test('proposal adoption never confirms and imported choices retain explicit origin',()=>{const s=setup();const {request,plan}=preview(s);assert.equal(s.draft.analyzed,false);assert.equal(s.plannerPreview.adopted,false);s.adoptPlanner({locale:'en'});assert.equal(s.draft.title,'');assert.equal(s.draft.summary,'');assert.equal(s.draft.metadata.narrationMode,'none');assert.deepEqual(s.draft.planner.plan.title,plan.title);assert.deepEqual(s.draft.planner.plan.reflection,plan.reflection);assert.equal(s.canPrint,false);assert.equal(s.draft.fieldEvidence.sky.origin,'imported-proposal');s.confirm();s.print();assert.ok(s.spec.choices.every(c=>c.origin==='imported-proposal'));assert.equal(s.printed.story.planner.origin,'imported-proposal');assert.equal(s.printed.story.plannerSnapshot.generation,request.generation);});
test('proposal contradicting literal supported choice creates required manual conflict',()=>{const s=setup('A flying teal whale carries a small city at night with a garden.');const {request,plan}=preview(s);plan.proposals.sky.value='sunset';plan.proposals.whaleColor.value='indigo';s.previewPlanner(plan,{request,origin:'ai-proposal'});s.adoptPlanner();const required=s.draft.issues.filter(i=>i.required);assert.ok(required.some(i=>i.field==='sky'));assert.ok(required.some(i=>i.field==='whaleColor'));assert.throws(()=>s.acknowledge(required[0].id,true));assert.throws(()=>s.confirm());s.updateBlueprint({world:{sky:'night',whaleColor:'teal'}});ack(s);s.confirm();s.print();assert.equal(s.spec.world.sky,'night');assert.equal(s.spec.world.whaleColor,'teal');});
test('planner cannot erase required alternate-world/invariant issue or unmet wish',()=>{for(const source of ['A dragon carrying a castle.','A flying whale carries a city with singing butterflies.']){const s=setup(source);preview(s);s.adoptPlanner();const issues=s.draft.issues;assert.ok(issues.length>0);if(source.includes('dragon')){ack(s);assert.equal(s.canConfirm,false);}else {assert.equal(s.canConfirm,false);ack(s);s.confirm();s.print();assert.ok(s.printed.unmetDetails.some(i=>i.fulfilled===false));}}});
test('stale response after every edit/reset/context change rejects without committing preview',()=>{for(const edit of [s=>s.setStory('New story'),s=>s.setRevisionText('night'),s=>s.updateBlueprint({title:'Changed'}),s=>s.invalidatePlanner(),s=>s.reset()]){const s=setup(),{request,plan}=preview(s);edit(s);assert.equal(s.plannerPreview,null);assert.throws(()=>s.previewPlanner(plan,{request}),/stale-planner/);assert.throws(()=>s.adoptPlanner(),/stale-planner/);assert.equal(s.printed.story,null);}});
test('malformed preview is atomic and does not replace last accepted preview',()=>{const s=setup(),{request,plan}=preview(s),prior=s.plannerPreview,draft=s.draft;const bad=structuredClone(plan);bad.proposals.sky.evidence=[{source:'sourceText',start:0,end:1,text:'bogus'}];assert.throws(()=>s.previewPlanner(bad,{request}));assert.deepEqual(s.plannerPreview,prior);assert.deepEqual(s.draft,draft);});
test('prompt export contains exact source/schema and no credential or claimed live success',()=>{const p=buildPlannerPrompt(snapshotForFixture('en-whale'));assert.equal(p.snapshot.sourceText,snapshotForFixture('en-whale').sourceText);assert.equal(p.schema.additionalProperties,false);assert.match(p.scope,/not live success/);assert.equal('apiKey' in p,false);});
test('synthetic fixture gate compares actual bytes/context, not client labels',()=>{const s=snapshotForFixture('vi-whale',42);assert.deepEqual(requireLiveFixture('vi-whale',s),s);for(const mutate of [s=>s.sourceText+=' private input',s=>s.mentorNotes='private adult note',s=>s.answerNotes=['private answer'],s=>s.ageBand='6-8']){const changed=structuredClone(s);mutate(changed);assert.throws(()=>requireLiveFixture('vi-whale',changed),/fixture-only/);}assert.throws(()=>requireLiveFixture('unknown',s));});

test('identical original/planner unmet review merges with provenance and ack; different wishes/sources remain separate',()=>{const source='Con muốn một cá voi bay chở thành phố có cửa hàng kẹo.';const first=setup(source);preview(first,context,'prepared-planner');first.adoptPlanner();assert.equal(first.draft.issues.filter(i=>!i.required&&!i.resolved).length,1);assert.equal(first.draft.issues[0].plannerReferences[0].origin,'prepared-planner');const s=setup(source);s.analyze();const original=s.draft.issues[0];s.acknowledge(original.id,true);const {request,plan}=preview(s,{...context,mentorNotes:source},'prepared-planner');const differentWish=structuredClone(plan.unrendered[0]);differentWish.id='another-wish';differentWish.reason={vi:'Một chi tiết khác chưa dựng.',en:'A different unrendered detail.'};plan.unrendered.push(differentWish);const differentSource=structuredClone(plan.unrendered[0]);differentSource.id='adult-source';differentSource.evidence=differentSource.evidence.map(q=>({...q,source:'mentorNotes'}));plan.unrendered.push(differentSource);s.previewPlanner(plan,{request,origin:'prepared-planner'});s.adoptPlanner();const issues=s.draft.issues.filter(i=>!i.required&&!i.resolved);assert.equal(issues.length,3);assert.equal(s.draft.acknowledgements[original.id],true);assert.equal(s.canConfirm,false);assert.equal(issues.find(i=>i.id===original.id).plannerReferences.length,1);});
