import test from 'node:test';
import assert from 'node:assert/strict';
import {analyzeStory,createStorySession,LIMITS} from '../story.js';
import {BASE_SPEC} from '../world.js';
const GOOD='A flying whale carries a city at sunset, no garden, no star bridge, indigo.';
function fixture(){let fail=false,calls=0;const s=createStorySession({initialArtifact:{prepared:true},compile:spec=>{calls++;if(fail)throw Error('synthetic compiler failure');return {id:calls,spec};}});return {s,fail:v=>fail=v,get calls(){return calls;}};}
function review(s,source=GOOD){s.setStory(source);s.analyze();for(const i of s.draft.issues)if(!i.required)s.acknowledge(i.id,true);s.confirm();}
function acknowledge(s){for(const i of s.draft.issues)if(!i.required)s.acknowledge(i.id,true);}
function exactQuotes(d){for(const q of [...Object.values(d.fieldEvidence).flatMap(x=>x.quotes),...d.issues.flatMap(x=>x.evidence)]){const input=q.source==='prior-print'?q.sourceTextSnapshot:d[q.source];assert.equal(input.slice(q.start,q.end),q.text);if(q.source==='prior-print'){assert.ok(q.printId>0);assert.ok(['sourceText','revisionText'].includes(q.sourceField));}}}
test('S01/S02 supported VI and EN fields with literal provenance',()=>{const vi=analyzeStory('Con muốn một cá voi màu xanh ngọc bay chở thành phố nhỏ. Ban đêm có khu vườn và cây cầu sao.');assert.deepEqual(vi.world,{sky:'night',cityScale:.8,gardens:true,starBridge:true,whaleColor:'teal'});assert.deepEqual(vi.issues,[]);exactQuotes(vi);const en=analyzeStory('A flying teal whale carries a tiny city at sunset, with a garden but no star bridge.');assert.deepEqual(en.world,{sky:'sunset',cityScale:.8,gardens:true,starBridge:false,whaleColor:'teal'});exactQuotes(en);});
test('S03 conflicting sky cannot confirm; explicit field correction is provenance',()=>{const {s}=fixture();s.setStory('Con muốn một cá voi bay chở thành phố. Trời vừa là ban đêm vừa là hoàng hôn.');s.analyze();assert.equal(s.draft.issues.filter(i=>i.kind==='unmet').length,0);assert.throws(()=>s.confirm(),/unresolved/);s.updateBlueprint({world:{sky:'night'}});acknowledge(s);s.confirm();assert.deepEqual(s.draft.fieldEvidence.sky.quotes,[]);assert.equal(s.draft.fieldEvidence.sky.status,'manual-choice');const en=analyzeStory('A flying whale city with both night and sunset.');assert.ok(en.issues.some(i=>i.kind==='conflict'&&i.required));assert.ok(!en.issues.some(i=>i.kind==='unmet'));});
test('S04 alternate creature never becomes printable whale',()=>{for(const source of ['Con muốn một con rồng sống trong rừng kẹo.','A dragon carrying a castle.','Replace the whale with a dragon carrying a city.']){const {s}=fixture();s.setStory(source);s.analyze();acknowledge(s);assert.equal(s.canConfirm,false);assert.throws(()=>s.confirm());assert.throws(()=>s.print());assert.equal(s.printed.story,null);}});
test('S05 optional unmet original words require omission acknowledgement',()=>{const {s}=fixture();s.setStory('Cá voi bay chở thành phố và một quán bán kẹo bông biết nói.');s.analyze();const i=s.draft.issues.find(i=>i.kind==='unmet');assert.ok(i.message.vi.includes('kẹo'));assert.equal(s.canConfirm,false);s.acknowledge(i.id,true);s.confirm();s.print();assert.equal(s.printed.unmetDetails[0].fulfilled,false);assert.equal(s.printed.unmetDetails[0].acknowledged,true);});
test('S06 VI/EN negation retains disabled boolean choices',()=>{for(const source of ['Cá voi bay chở thành phố. Không có khu vườn và không có cầu sao.','A flying whale city without a garden and no star bridge.']){const d=analyzeStory(source);assert.equal(d.world.gardens,false);assert.equal(d.world.starBridge,false);}});
test('S07 unspecified values are proposals with no fabricated quotes',()=>{const d=analyzeStory('A flying whale with a city.');assert.equal(d.world.sky,'sunset');assert.equal(d.fieldEvidence.sky.status,'default-proposal');assert.equal(d.fieldEvidence.sky.origin,'offline-suggestion');assert.deepEqual(d.fieldEvidence.sky.quotes,[]);});
test('S08/S10 revisions preserve unrelated choices and seed',()=>{const {s}=fixture();review(s,'A flying teal whale carries a tiny city at night with a star bridge.');s.print();const before=s.spec;s.requestRevision('Thêm một khu vườn nhưng giữ nguyên trời đêm.');acknowledge(s);s.confirm();s.print();assert.equal(s.spec.world.gardens,true);for(const k of ['sky','cityScale','starBridge','whaleColor'])assert.equal(s.spec.world[k],before.world[k]);assert.equal(s.spec.seed,before.seed);s.requestRevision('Remove the garden and keep the star bridge.');acknowledge(s);s.confirm();s.print();assert.equal(s.spec.world.gardens,false);assert.equal(s.spec.world.starBridge,true);exactQuotes(s.draft);});
test('S09 invariant removal cannot be resolved by optional acknowledgement or manual fields',()=>{for(const source of ['Cá voi bay chở thành phố, không có cá voi.','Cá voi bay chở thành phố, không có thành phố.','A flying whale city with no whale.']){const {s}=fixture();s.setStory(source);s.analyze();const i=s.draft.issues.find(i=>i.kind==='invariant');assert.ok(i?.required);assert.throws(()=>s.acknowledge(i.id,true));s.updateBlueprint({world:{sky:'night'}});assert.equal(s.canConfirm,false);}const {s}=fixture();review(s);s.print();const before=s.printed;s.requestRevision('Bỏ cá voi đi, chỉ giữ lại thành phố trên mặt đất.');assert.equal(s.canConfirm,false);assert.deepEqual(s.printed,before);});
test('S11 every edit and invalid attempt invalidate confirmation; undo does not restore it',()=>{for(const edit of [s=>s.setStory(GOOD),s=>s.updateBlueprint({title:'Edited'}),s=>s.updateBlueprint({summary:'Edited'}),s=>s.updateBlueprint({world:{gardens:true}}),s=>s.setRevisionText('night'),s=>s.acknowledge(s.draft.issues.find(i=>!i.required).id,false),s=>assert.throws(()=>s.updateBlueprint({world:{cityScale:50}}))]){const {s}=fixture();review(s,GOOD+' Singing butterflies.');s.print();const before=s.printed;edit(s);assert.equal(s.canPrint,false);assert.throws(()=>s.print());assert.deepEqual(s.printed,before);}const {s}=fixture();review(s);s.updateBlueprint({title:'temporary'});s.updateBlueprint({title:'Bản thiết kế / World draft'});assert.equal(s.canPrint,false);});
test('S12 stale analysis tickets cannot overwrite current source or reset',()=>{const {s}=fixture();s.setStory(GOOD);const ticket=s.analysisTicket;s.setStory('A whale city at night');const before=s.draft;assert.throws(()=>s.analyze({expectedRevision:ticket}),/stale/);assert.deepEqual(s.draft,before);s.reset();assert.throws(()=>s.analyze({expectedRevision:ticket}));assert.equal(s.draft.sourceText,'');});
test('S12 compiler and reset failures preserve last-good story/artifact/history',()=>{const f=fixture(),{s}=f;review(s);s.print();const before={p:s.printed,h:s.history,a:s.artifact};s.requestRevision('Add a garden.');acknowledge(s);s.confirm();f.fail(true);assert.throws(()=>s.print());assert.deepEqual(s.printed,before.p);assert.deepEqual(s.history,before.h);assert.equal(s.artifact,before.a);assert.throws(()=>s.reset());assert.deepEqual(s.printed,before.p);assert.deepEqual(s.history,before.h);assert.equal(s.artifact,before.a);assert.equal(s.draft.revisionText,'Add a garden.');});
test('prior unmet details and omission acceptance persist across two unrelated revisions',()=>{const {s}=fixture();review(s,GOOD+' Singing butterflies.');s.print();s.requestRevision('night');assert.ok(s.draft.issues.some(i=>i.kind==='unmet'));assert.equal(s.canConfirm,true);s.confirm();s.print();s.requestRevision('Add a garden.');acknowledge(s);s.confirm();s.print();const retained=s.printed.unmetDetails.find(i=>i.evidence.some(q=>q.text.includes('Singing butterflies')));assert.equal(retained.fulfilled,false);assert.equal(retained.acknowledged,true);assert.ok(retained.evidence.every(q=>q.source==='prior-print'));exactQuotes(s.draft);});
test('Unicode emoji and NFD exact quotes survive repeated revisions',()=>{for(const source of ['✨ Cá voi bay chở thành phố vào hoàng hôn, màu xanh ngọc.','✨ Cá voi bay chở thành phố vào hoàng hôn, màu xanh ngọc.'.normalize('NFD')]){const {s}=fixture();review(s,source);exactQuotes(s.draft);s.print();s.requestRevision('Đổi sang đêm.');acknowledge(s);exactQuotes(s.draft);s.confirm();s.print();s.requestRevision('Thêm khu vườn.');exactQuotes(s.draft);assert.ok(s.draft.fieldEvidence.sky.quotes.some(q=>q.sourceField==='revisionText'));}});
test('prepared fixtures, initial scene and session input never imply authenticated child identity',()=>{const {s}=fixture();assert.equal(s.printed.story,null);assert.equal(s.printed.confirmedInSession,false);s.loadPreparedExample(GOOD);s.analyze();acknowledge(s);s.confirm();s.print();assert.equal(s.printed.dataKind,'prepared-synthetic-demo');s.setStory(GOOD);assert.equal(s.draft.dataKind,'local-session-story');s.analyze();acknowledge(s);s.confirm();s.print();assert.ok(s.spec.choices.every(c=>c.origin!=='child'&&c.status==='confirmed-in-session'));assert.equal(s.printed.story.sourceKind,'local-session-story');});
test('title/summary-only print updates metadata without geometry rebuild/version change',()=>{const f=fixture(),{s}=f;review(s);s.print();const a=s.artifact,v=s.spec.version,c=f.calls;s.updateBlueprint({title:'New title',summary:'Human edited summary'});s.confirm();const result=s.print();assert.equal(s.printed.story.title,'New title');assert.equal(s.spec.version,v);assert.equal(s.artifact,a);assert.equal(f.calls,c);assert.equal(result.changed,false);assert.equal(result.rebuilt,false);assert.equal(s.history.length,2);});
test('no-op reprint reuses artifact but records exact printed metadata',()=>{const {s}=fixture();review(s);s.print();const a=s.artifact,v=s.spec.version;s.print();assert.equal(s.artifact,a);assert.equal(s.spec.version,v);assert.equal(s.history.at(-1).changed,false);});
test('getter mutations or supplied print overrides cannot alter confirmed blueprint',()=>{const {s}=fixture();review(s);s.draft.world.gardens=true;s.confirmation.spec.world.gardens=true;assert.throws(()=>s.print({world:{gardens:true}}),/invalid-print-input/);s.print();assert.equal(s.spec.world.gardens,false);});
test('pending plain-language edits require explicit revision review',()=>{const {s}=fixture();review(s);s.print();s.setRevisionText('night');assert.equal(s.canConfirm,false);assert.throws(()=>s.analyze(),/revision-not-reviewed/);assert.throws(()=>s.confirm());s.requestRevision(s.draft.revisionText);assert.equal(s.draft.mode,'revision');assert.equal(s.draft.world.sky,'night');});
test('unsupported sky/color is necessary unknown until explicit correction and omission disclosure',()=>{for(const [source,field,value] of [['A flying whale city at sunrise.','sky','sunset'],['A flying red whale city.','whaleColor','indigo']]){const {s}=fixture();s.setStory(source);s.analyze();assert.equal(s.canConfirm,false);s.updateBlueprint({world:{[field]:value}});acknowledge(s);s.confirm();s.print();assert.ok(s.printed.unmetDetails.some(i=>i.fulfilled===false));}});
test('explicit transition night to sunset wins only a supported target',()=>{const d=analyzeStory(GOOD,{priorSpec:{...BASE_SPEC,world:{...BASE_SPEC.world,sky:'night'}},priorStory:{},priorPrintId:1,revisionText:'Change night to sunset.'});assert.equal(d.world.sky,'sunset');assert.ok(!d.issues.some(i=>i.kind==='conflict'));});
test('input limits/unknown patch keys reject atomically with exact source preserved',()=>{const {s}=fixture();s.setStory('  '+GOOD+'\n');const exact=s.draft.sourceText;for(const call of [()=>s.setStory('x'.repeat(LIMITS.story+1)),()=>s.setRevisionText('x'.repeat(LIMITS.revision+1)),()=>s.updateBlueprint({script:'evil'}),()=>s.updateBlueprint({world:{extra:true}})])assert.throws(call);assert.equal(s.draft.sourceText,exact);});
test('successful reset clears source, acknowledgements, history and confirmation',()=>{const {s}=fixture();review(s,GOOD+' Singing butterflies.');s.print();s.reset();assert.equal(s.draft.sourceText,'');assert.deepEqual(s.draft.acknowledgements,{});assert.deepEqual(s.history,[]);assert.equal(s.printed.story,null);assert.equal(s.canPrint,false);assert.equal(s.spec.version,1);});
test('JSON export is isolated, literal HTML input remains data, no provider or storage fields',()=>{const {s}=fixture();review(s,GOOD+' <img src=x onerror=alert(1)>');s.print();const exported=s.exportProject();assert.match(exported.printed.story.sourceText,/<img/);exported.printed.spec.world.gardens=true;assert.equal(s.spec.world.gardens,false);assert.ok(exported.printed.unmetDetails.every(i=>!i.fulfilled));assert.equal(exported.schemaVersion,1);assert.equal('apiKey' in exported,false);assert.equal('storage' in exported,false);});

test('bounded negative add forms disable choices; double negative removal requires correction',()=>{for(const [source,key] of [['A flying whale city, do not add a garden.','gardens'],["A flying whale city, don't add a star bridge.",'starBridge'],['Cá voi bay chở thành phố, đừng thêm khu vườn.','gardens']]){const d=analyzeStory(source);assert.equal(d.world[key],false);assert.ok(d.fieldEvidence[key].quotes[0].text.match(/(?:not add|don't add|đừng thêm)/));exactQuotes(d);}for(const source of ['A flying whale city, do not remove the garden.',"A flying whale city, don't remove the garden.",'Cá voi bay chở thành phố, đừng bỏ khu vườn.']){const d=analyzeStory(source);assert.ok(d.issues.some(i=>i.required&&i.field==='gardens'));}});

test('forged retained-prior quote spans are rejected rather than legitimized',()=>{assert.throws(()=>analyzeStory(GOOD,{priorSpec:BASE_SPEC,priorPrintId:1,revisionText:'night',priorStory:{sourceText:GOOD,fieldEvidence:{sky:{quotes:[{source:'sourceText',start:0,end:4,text:'fake'}]}}}}),/invalid-prior-evidence/);});
