import test from 'node:test';import assert from 'node:assert/strict';
import {BASE_SPEC,validateWorldSpec,layoutPlan,createWorldSession,worldDiff} from '../world.js';
const copy=()=>structuredClone(BASE_SPEC);
test('strict schema rejects extra keys, invalid ranges, nonfinite fields and malformed invariants',()=>{for(const mutate of [s=>s.extra=true,s=>s.world.extra=true,s=>s.schemaVersion=1,s=>s.version=0,s=>s.version=101,s=>s.seed=0,s=>s.seed=1e6,s=>s.world.cityScale=NaN,s=>s.world.cityScale=Infinity,s=>s.world.cityScale=.79,s=>s.world.gardens=1,s=>s.invariants.reverse(),s=>s.dataKind='real-child-record']){const s=copy();mutate(s);assert.throws(()=>validateWorldSpec(s));}});
test('choice contract rejects duplicate IDs, >16, unknown provenance/status and oversized descriptions',()=>{for(const mutate of [s=>s.choices.push(structuredClone(s.choices[0])),s=>s.choices=Array.from({length:17},(_,i)=>({...s.choices[0],id:'id-'+i})),s=>s.choices[0].origin='verified-child',s=>s.choices[0].status='approved-by-child',s=>s.choices[0].description.vi='x'.repeat(501),s=>s.choices[0].description.extra='x']){const s=copy();mutate(s);assert.throws(()=>validateWorldSpec(s));}});
test('validation isolates return and layout is deterministic P01-compatible geometry',()=>{const s=copy(),validated=validateWorldSpec(s);validated.world.gardens=true;assert.equal(s.world.gardens,false);const plan=layoutPlan(s);assert.deepEqual(plan,layoutPlan(s));assert.equal(plan.houses.length,12);assert.equal(plan.stars.length,100);assert.equal(plan.lanterns.length,5);const changed=copy();changed.seed++;assert.notDeepEqual(plan,layoutPlan(changed));});
test('diff reports only supported changed render fields',()=>{const a=copy(),b=copy();b.world.gardens=true;b.dataKind='local-session-story';assert.deepEqual(worldDiff(a,b),[{key:'gardens',before:false,after:true}]);});
test('transaction validates version and commits compile only after success',()=>{let fail=false,calls=0;const initial={name:'last-good'},s=createWorldSession(()=>{calls++;if(fail)throw Error('fault');return {calls};},()=>{},{initialArtifact:initial});const next=copy();next.world.gardens=true;next.version=2;fail=true;assert.throws(()=>s.print(next));assert.equal(s.artifact,initial);assert.deepEqual(s.spec,BASE_SPEC);assert.deepEqual(s.history,[]);fail=false;s.print(next);assert.equal(s.spec.version,2);assert.equal(s.spec.world.gardens,true);assert.throws(()=>s.print({...next,version:3}));});
test('no-op metadata reuses artifact; seed change requires version increment/rebuild',()=>{let calls=0;const s=createWorldSession(()=>({id:++calls}),()=>{},{initialArtifact:{initial:true}});const metadata=copy();metadata.dataKind='local-session-story';assert.equal(s.print(metadata).rebuilt,false);assert.equal(calls,0);const seed=copy();seed.seed++;seed.version=2;const result=s.print(seed);assert.equal(result.changed,true);assert.equal(calls,1);});
test('version limit blocks 101 without compile or partial commit',()=>{const initial=copy();initial.version=100;let called=false;const s=createWorldSession(()=>{called=true;return {};},()=>{},{initialSpec:initial,initialArtifact:{}});const next=structuredClone(initial);next.world.gardens=true;next.version=101;assert.throws(()=>s.print(next));assert.equal(called,false);assert.equal(s.spec.version,100);});
test('thenable/falsy compiler and failed reset keep artifact/history; successful reset clears history',()=>{let kind='good';const initial={initial:true},s=createWorldSession(()=>kind==='throw'?(()=>{throw Error('fault')})():kind==='null'?null:kind==='promise'?Promise.resolve({}):{},()=>{},{initialArtifact:initial});const next=copy();next.world.sky='night';next.version=2;for(const fault of ['throw','null','promise']){kind=fault;assert.throws(()=>s.print(next));assert.equal(s.artifact,initial);assert.deepEqual(s.history,[]);}kind='good';s.print(next);const a=s.artifact,h=s.history;kind='throw';assert.throws(()=>s.reset());assert.equal(s.artifact,a);assert.deepEqual(s.history,h);kind='good';s.reset();assert.deepEqual(s.history,[]);assert.deepEqual(s.spec,BASE_SPEC);});
test('disposal occurs after commit; cleanup fault does not undo valid new world',()=>{let disposed=0;const old={},s=createWorldSession(()=>({new:true}),()=>{disposed++;throw Error('cleanup');},{initialArtifact:old});const next=copy();next.world.gardens=true;next.version=2;s.print(next);assert.equal(s.spec.version,2);assert.notEqual(s.artifact,old);assert.equal(disposed,1);assert.deepEqual(s.cleanupErrors,['dispose-failed']);});

test('prepared baseline is deeply immutable and cannot change reset defaults',()=>{assert.throws(()=>{BASE_SPEC.world.sky='night';});assert.throws(()=>{BASE_SPEC.choices[0].origin='child';});assert.equal(BASE_SPEC.world.sky,'sunset');});
