import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs/promises';import path from'node:path';import os from'node:os';import{buildSite,verifySite,collectSite}from'../build_site.mjs';
const source=new URL('../../app/',import.meta.url);
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'static-site-test-'));await fs.cp(source,path.join(root,'app'),{recursive:true});t.after(()=>fs.rm(root,{recursive:true,force:true}));return root}
test('same output for full Git checkout despite development/source inputs; deterministic exact build',async t=>{const r=await fixture(t);await fs.writeFile(path.join(r,'app/dream/private-session.json'),'SYNTHETIC PRIVATE MARKER');const a=await buildSite(r),b=await buildSite(r);assert.deepEqual(a,b);assert.deepEqual(await verifySite(r),a);for(const n of['dream/private-session.json','dream/tests/public-mode.test.mjs','tests/model.test.mjs','dream/kit/render.py','dream/kit/BUILD.json','dream/kit/CONTENT.json','dream/DEPENDENCIES.json','resources/manifest.json','references/build.json','package.json','README.md'])assert.equal(n in a.files,false,n);for(const n of['index.html','dream/index.html','dream/vendor/THREE-LICENSE.txt','dream/kit/rehearsal.en.html','dream/kit/observation.csv','downloads/project-review-WEB02.zip'])assert.equal(n in a.files,true,n)});
test('modified generated observation sheet fails before replacing last-good output',async t=>{const r=await fixture(t),before=await buildSite(r);await fs.appendFile(path.join(r,'app/dream/kit/observation.csv'),'FORGED RESULT');await assert.rejects(buildSite(r),/kit generated source drift/);assert.equal(JSON.parse(await fs.readFile(path.join(r,'.vercel/static-site-receipt.json'))).fingerprint,before.fingerprint)});
test('compiler path traversal and changed compiled bytes fail loudly',async t=>{const r=await fixture(t),f=path.join(r,'app/resources/manifest.json'),original=await fs.readFile(f),m=JSON.parse(original);m.outputs['../private-session.json']='fake';await fs.writeFile(f,JSON.stringify(m));await assert.rejects(collectSite(r),/unsafe static source path/);await fs.writeFile(f,original);await fs.appendFile(path.join(r,'app/resources/catalog.json'),'FORGED');await assert.rejects(collectSite(r),/compiled source drift/)});
test('symlinked runtime asset cannot copy an outside source',async t=>{const r=await fixture(t),f=path.join(r,'app/dream/vendor/THREE-LICENSE.txt');await fs.unlink(f);await fs.symlink('/etc/hosts',f);await assert.rejects(buildSite(r),/static source symlink/)});
test('missing required local vendor license fails, without deleting existing output',async t=>{const r=await fixture(t);await buildSite(r);const before=await fs.readFile(path.join(r,'dist/dream/vendor/THREE-LICENSE.txt'));await fs.unlink(path.join(r,'app/dream/vendor/THREE-LICENSE.txt'));await assert.rejects(buildSite(r),/ENOENT/);assert.deepEqual(await fs.readFile(path.join(r,'dist/dream/vendor/THREE-LICENSE.txt')),before)});
test('output byte tamper fails integrity and an exact managed rebuild repairs it',async t=>{const r=await fixture(t);await buildSite(r);await fs.appendFile(path.join(r,'dist/dream/main.js'),'BAD OUTPUT');await assert.rejects(verifySite(r),/static output bytes drift/);await buildSite(r);await verifySite(r)});
test('unknown output and unowned directory are never silently deleted',async t=>{const r=await fixture(t);await fs.mkdir(path.join(r,'dist'));await fs.writeFile(path.join(r,'dist/private-note.txt'),'synthetic');await assert.rejects(buildSite(r),/unmanaged dist/);await fs.rm(path.join(r,'dist'),{recursive:true});await buildSite(r);await fs.writeFile(path.join(r,'dist/private-note.txt'),'synthetic');await assert.rejects(verifySite(r),/output inventory drift/);await assert.rejects(buildSite(r),/unlisted dist content/);assert.equal(await fs.readFile(path.join(r,'dist/private-note.txt'),'utf8'),'synthetic')});
test('changed download archive is rejected against its exact outer receipt',async t=>{const r=await fixture(t);await fs.appendFile(path.join(r,'app/downloads/project-review-WEB02.zip'),'BAD ARCHIVE');await assert.rejects(collectSite(r),/archive\/receipt drift/)});

test('integrity checks reject output/metadata root and receipt symlinks before reading',async t=>{for(const target of['dist','.vercel','.vercel/static-site-receipt.json']){const r=await fixture(t);await buildSite(r);const actual=path.join(r,target),moved=path.join(r,'owned-outside-'+target.replaceAll('/','-'));await fs.rename(actual,moved);await fs.symlink(moved,actual);await assert.rejects(verifySite(r),/symlink/);await assert.rejects(buildSite(r),/symlink/);}});

test('reference compiler receipt is an input only and changed catalog/report bytes are rejected',async t=>{const r=await fixture(t),site=await buildSite(r);assert.ok(site.inputs['app/references/build.json']);assert.equal('references/build.json'in site.files,false);await fs.appendFile(path.join(r,'app/references/report.html'),'FORGED');await assert.rejects(collectSite(r),/reference generated source drift/);});
test('Vercel directory normalization is required for correct module/kit relative URLs; file extensions remain direct',async()=>{const config=JSON.parse(await fs.readFile(new URL('../../vercel.json',import.meta.url)));assert.equal(config.trailingSlash,true);assert.equal(config.outputDirectory,'dist');assert.equal(config.buildCommand,'node tools/build_site.mjs');for(const[entry,resource,expected]of[['/dream/?lang=en','main.js','/dream/main.js'],['/dream/?lang=vi','vendor/three.module.js','/dream/vendor/three.module.js'],['/dream/kit/?lang=en','rehearsal.en.html','/dream/kit/rehearsal.en.html'],['/dream/kit/?lang=vi','observation.csv','/dream/kit/observation.csv']])assert.equal(new URL(resource,'https://example.test'+entry).pathname,expected);assert.ok(!config.cleanUrls);});
