// Authored remote-review surfaces. Visitor feedback is separate from the learning model.
export const REVIEW_KEY='thuy-anh-ai-learning:project-review:v1';
export const REVIEW_FIELDS=['name','problem','product','lesson','operations','next'];
export const VIEWS=['overview','guide','review','group','activity','session','reports','library','workbench'];
const clone=value=>JSON.parse(JSON.stringify(value));
export function parseRoute(hash=''){
 const raw=String(hash).replace(/^#/,'');if(!raw)return {view:'overview',doc:null,lesson:null,lang:null,error:null};
 const [view,query,...extra]=raw.split('?');if(extra.length||!VIEWS.includes(view))return {view:'overview',doc:null,lesson:null,lang:null,error:'invalid-route'};
 let params;try{params=new URLSearchParams(query??'');}catch{return {view,doc:null,lesson:null,lang:null,error:'invalid-route'};}
 for(const key of params.keys())if(!['doc','lang','lesson'].includes(key)||params.getAll(key).length!==1)return {view,doc:null,lesson:null,lang:null,error:'invalid-route'};
 const lang=params.get('lang'),doc=params.get('doc'),lesson=params.get('lesson');if(lang!==null&&!['vi','en'].includes(lang))return {view,doc:null,lesson:null,lang:null,error:'invalid-language'};
 if(doc!==null&&(view!=='library'||! /^[A-Z0-9][A-Z0-9_-]{1,99}$/.test(doc)))return {view,doc:null,lesson:null,lang,error:'invalid-document'};
 if(lesson!==null&&(!['group','activity'].includes(view)||! /^[A-Z0-9][A-Z0-9_-]{1,99}$/.test(lesson)))return {view,doc:null,lesson:null,lang,error:'invalid-lesson'};
 return {view,doc,lesson,lang,error:null};
}
export function documentHash(id,locale){if(!/^[A-Z0-9][A-Z0-9_-]{1,99}$/.test(id)||!['vi','en'].includes(locale))throw new Error('Invalid document link');return `#library?doc=${encodeURIComponent(id)}&lang=${locale}`;}
export function sharedDocumentURL(origin,id,locale){const url=new URL(origin);if(!['http:','https:'].includes(url.protocol)||url.username||url.password)throw new Error('Invalid page origin');url.search='';url.hash=documentHash(id,locale);return url.href;}
export function freshReview(){return {schemaVersion:1,kind:'adult-project-review',status:'visitor-draft-not-approval',name:'',problem:'',product:'',lesson:'',operations:'',next:'',updatedAt:new Date().toISOString(),uiLocaleAtSave:'vi'};}
export function validateReview(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!['schemaVersion','kind','status','updatedAt','uiLocaleAtSave',...REVIEW_FIELDS].includes(k))||input.schemaVersion!==1||input.kind!=='adult-project-review'||input.status!=='visitor-draft-not-approval'||!['vi','en'].includes(input.uiLocaleAtSave)||typeof input.updatedAt!=='string'||input.updatedAt.length>50||!Number.isFinite(Date.parse(input.updatedAt))||REVIEW_FIELDS.some(k=>typeof input[k]!=='string'||input[k].length>(k==='name'?200:4000)))throw new Error('invalid-review');return clone(input);}
export function loadReview(storage){try{const raw=storage.getItem(REVIEW_KEY);if(raw===null||raw===undefined)return {review:freshReview(),error:null,protected:false,stored:false};if(raw.length>100000)throw Error('invalid-review');return {review:validateReview(JSON.parse(raw)),error:null,protected:false,stored:true};}catch{return {review:freshReview(),error:'review-read-error',protected:true,stored:false};}}
export function updateReview(review,field,value,locale){if(!REVIEW_FIELDS.includes(field))throw Error('invalid-review-field');const next={...review,[field]:value,updatedAt:new Date().toISOString(),uiLocaleAtSave:locale};return validateReview(next);}
export function saveReview(storage,review,protectedStore=false){if(protectedStore)return 'review-protected';try{storage.setItem(REVIEW_KEY,JSON.stringify(validateReview(review)));return null;}catch{return 'review-save-error';}}
export function reviewMarkdown(review,locale='vi'){const checked=validateReview(review),c=COPY[locale]??COPY.vi;return [`# ${c.reviewTitle}`,c.reviewScope,`Updated: ${checked.updatedAt}`,`UI language at save: ${checked.uiLocaleAtSave}`,'',...REVIEW_FIELDS.flatMap(key=>[`## ${c.fields[key][0]}`,checked[key]||c.empty,'']),'---',c.localOnly].join('\n');}
const E=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const docs=(id,label,locale)=>`<a href="${documentHash(id,locale)}">${E(label)}</a>`;
export const COPY={
 vi:{
 overview:'Dự án',guide:'Lộ trình xem',review:'Góp ý',skip:'Bỏ qua điều hướng, đến nội dung',
 title:'Cùng trẻ học cách kiểm chứng AI.',intro:'Một bộ công cụ để người lớn hướng dẫn người học đọc nguồn, nhận ra điều chưa biết và tự giải thích kết luận của mình. AI có thể đưa ra một câu trả lời; người học vẫn cần biết vì sao nên tin, sửa hoặc dừng lại.',
 start:'Xem dự án theo lộ trình',lessonAction:'Xem bài “Đọc đúng lời hẹn”',libraryAction:'Khám phá toàn bộ thư viện',
 scope:'Bản làm việc dành cho người lớn xem xét và diễn tập. Học liệu, rubric và mô hình sản phẩm vẫn cần được rà soát cùng người có chuyên môn.',
 exampleTitle:'Một lời hẹn, hai thông báo.',example:'Trong LES-02, thông báo cập nhật đổi giờ và địa điểm. Phản hồi AI mẫu vẫn dùng bản cũ và tự thêm điều không có trong nguồn. Người học tìm bằng chứng, sửa kết luận rồi làm một nhiệm vụ mới không có AI.',
 exampleNote:'CLB Mầm Lá và toàn bộ thông báo là tình huống tự soạn, hoàn toàn giả định. Phản hồi có lỗi có chủ đích để diễn tập, không phải kết quả của một provider thật.',
 design:'Đọc lý do thiết kế bài',eight:'Tám bước giữ lại quá trình suy nghĩ',steps:['Suy nghĩ ban đầu','Xem phản hồi AI mẫu','Chọn điều cần kiểm','Đối chiếu với nguồn','Sửa kết luận','Tự giải thích','Làm bài mới không AI','Người hướng dẫn ghi nhận'],
 stepsNote:'Bài ban đầu, bài có hỗ trợ và bài độc lập được giữ riêng. Điểm rubric do người hướng dẫn nhập; phần mềm không tự kết luận người học đã tiến bộ.',
 mapTitle:'Bản đồ dự án',mapIntro:'Từ một bài học cụ thể đến cách vận hành và cách xác định điều cần kiểm chứng.',
 map:[['Vấn đề và lựa chọn sản phẩm','MAT-01','Brief dự án','P03-CONTRACT','Product contract'],['Bài học và cách đo','P03-ANCHOR','Lý do thiết kế LES-02','P03-ASSESS','Bộ đo độc lập / trì hoãn'],['Nghiên cứu và giới hạn','P03-METHODS','Đọc phương pháp nghiên cứu','R01-GAPS','Khoảng trống bằng chứng'],['Diễn tập và trách nhiệm','P03-REHEARSE','Quy trình diễn tập','P03-DATA','Người tham gia và dữ liệu']],
 ready:'Có thể xem và thử trên máy',available:'Giao diện VI/EN, ba bài nháp, thư viện 54 tài liệu với các bản tiếng Anh, quan sát có cấu trúc, readiness và export. Tất cả hoạt động học dùng dữ liệu giả và phản hồi AI mẫu.',
 pending:'Cần cùng nhau quyết định',pendingText:'Chọn nhóm gia đình đầu tiên, vấn đề cần giải quyết, người rà soát sư phạm và cách dùng dữ liệu. Nhu cầu trả phí, kết quả diễn tập độc lập và hiệu quả với người học vẫn chưa được xác nhận.',
 feedbackAction:'Ghi lại góp ý của bạn',download:'Mang bộ dự án về máy',downloadIntro:'Bản tải gồm ứng dụng, học liệu VI/EN, metadata nghiên cứu và mẫu benchmark offline. Toàn văn bên thứ ba không nằm trong gói; tài liệu giữ liên kết nguồn ngoài.',zip:'Tải bộ dự án WEB02 từ website',manifest:'Xem danh mục và SHA-256 trên website',source:'Xem mã nguồn GitHub',downloadNote:'Các liên kết tải cần bản web đang hoạt động. Nếu bạn đã mở gói offline, giữ gói gốc hoặc quay lại trang web. Bấm liên kết chưa xác nhận file đã được lưu; kiểm tra file trên máy.',
 guideTitle:'Đi một vòng, hiểu dự án.',guideIntro:'Lộ trình dưới đây giúp xem được bài toán, trải nghiệm một bài cụ thể và ghi nhận điều cần sửa mà không cần người xây dựng ngồi cạnh.',routeTitle:'Đọc theo thứ tự',route:[['MAT-01','Bắt đầu từ điều đã biết','Brief phân biệt thông tin có nguồn, đề xuất và điều cần quyết định.'],['P03-CONTRACT','Chốt vấn đề đầu tiên','Xem các lựa chọn sản phẩm và những giả thuyết còn mở.'],['MAT-04','Đọc bài LES-02','Theo dõi tình huống, thẻ nguồn, phản hồi mẫu và hướng dẫn tám bước.'],['P03-ANCHOR','Hiểu vì sao bài được thiết kế như vậy','Xem mục tiêu, lý do và giới hạn của rubric, bài độc lập và đo trì hoãn.'],['P03-REHEARSE','Chuẩn bị một lượt diễn tập','Xem quy trình người lớn tự vận hành và cách ghi lại trợ giúp, thời gian, sự cố.'],['P03-METHODS','Đối chiếu với nghiên cứu','Đọc phạm vi áp dụng và phần chưa được xác nhận tại Việt Nam.'],['M01-ROADMAP','Chọn việc làm tiếp','Dùng kế hoạch và điều kiện nghiệm thu để ghi lại ưu tiên.']],
 tryTitle:'Thử trọn một buổi bằng dữ liệu giả',trySteps:['Vào Nhóm học, chọn LES-02 “Đọc đúng lời hẹn”. Dùng học viên mẫu hoặc thêm một mã giả.','Bắt đầu buổi. Ghi suy nghĩ ban đầu rồi mở phản hồi AI mẫu; có thể thử lỗi hoặc timeout và mở lại.','Đi hết phần kiểm nguồn, sửa kết luận, tự giải thích và bài mới không AI.','Người hướng dẫn ghi tên/mã giả, ba điểm rubric và ghi chú. Mở Báo cáo để xem các giai đoạn riêng.','Vào Diễn tập để ghi quan sát và điều còn thiếu. Xuất backup ứng dụng hoặc hồ sơ diễn tập nếu cần chuyển máy.'],
 areasTitle:'Các khu làm việc',areas:[['group','Nhóm học'],['activity','Soạn và rà soát hoạt động'],['session','Buổi thực hành'],['reports','Hồ sơ bài làm'],['library','Thư viện đầy đủ'],['workbench','Readiness và quan sát']],
 localTitle:'Bạn và người khác có kho riêng.',localOnly:'Dữ liệu nằm trong trình duyệt, thiết bị và địa chỉ web bạn đang dùng; không đồng bộ giữa hai người. Đổi host, port hoặc profile mở một kho khác. Backup ứng dụng chứa bài làm/phiên/quan sát; export góp ý ở đây là một hồ sơ riêng. Bạn tự chuyển file hoặc gửi cho người cộng tác qua kênh đã thống nhất.',
 reviewTitle:'Góp ý để chọn bước tiếp theo',reviewIntro:'Ghi phản hồi về dự án và bài học; tên là tùy chọn. Không nhập thông tin trẻ thật. Góp ý chỉ lưu trên máy của bạn, không tự gửi cho chủ dự án.',reviewScope:'Bản góp ý của người xem; không phải phê duyệt, consent hoặc kết quả học tập.',
 fields:{name:['Tên hoặc mã người xem (tùy chọn)','Có thể để trống.'],problem:['Vấn đề cần giải quyết','Gia đình đang gặp việc gì? Điều nào chưa rõ hoặc chưa đúng?'],product:['Lựa chọn sản phẩm','Hình thức nào đáng thử trước và vì sao?'],lesson:['Ngôn ngữ và thiết kế bài LES-02','Chỗ nào dễ hiểu, gây hiểu nhầm hoặc cần review sư phạm?'],operations:['Vận hành và trải nghiệm','Thao tác, thiết bị, backup hoặc hướng dẫn nào cần sửa?'],next:['Quyết định và việc tiếp theo','Ưu tiên nào cần thống nhất? Ai cần tham gia và còn thiếu bằng chứng gì?']},
 draftHint:'Nội dung được lưu trên trình duyệt này khi bạn nhập.',saved:'Góp ý đã lưu trên trình duyệt này.',empty:'Chưa ghi góp ý.',exportMarkdown:'Xuất góp ý Markdown',exportJSON:'Xuất góp ý JSON',reviewReadError:'Không đọc được bản góp ý đã lưu. Dữ liệu cũ được giữ nguyên; bản đang soạn chỉ ở bộ nhớ. Xuất file trước khi đóng.',reviewSaveError:'Trình duyệt chưa lưu được góp ý. Nội dung vẫn ở bộ nhớ; xuất file trước khi đóng.',reviewExportNote:'Export này chỉ chứa góp ý. Không thay backup ứng dụng; chưa có import góp ý hoặc gửi tự động.',routeError:'Liên kết chưa hợp lệ hoặc không tìm thấy tài liệu. Mở thư viện đầy đủ để chọn lại.',copyLink:'Chia sẻ liên kết tài liệu',linkExport:'Liên kết chia sẻ tài liệu'
 },
 en:{
 overview:'Project',guide:'Guided review',review:'Feedback',skip:'Skip navigation and go to content',
 title:'Help learners learn to verify AI.',intro:'A working kit for adults to guide learners through reading sources, recognising uncertainty and explaining their own conclusions. AI may offer an answer; learners still need to know why to trust it, revise it or stop.',
 start:'Follow the guided review',lessonAction:'Explore “Read the updated notice accurately”',libraryAction:'Browse the complete library',
 scope:'A working edition for adult review and rehearsal. Lessons, rubrics and product choices still need review with qualified people.',
 exampleTitle:'One invitation. Two notices.',example:'In LES-02, an updated notice changes the time and venue. The AI fixture repeats the old notice and adds claims absent from either source. Learners find evidence, revise their conclusion, then complete a new task without AI.',
 exampleNote:'The Mầm Lá club and all notices are entirely fictional, authored rehearsal materials. The response contains deliberate errors; it is not an observed response from a live provider.',design:'Read the lesson design rationale',eight:'Eight steps preserve the thinking process',steps:['Initial thinking','Inspect the AI fixture','Choose a claim to check','Check against sources','Revise the conclusion','Explain in your own words','Complete a new task without AI','Facilitator records the evidence'],
 stepsNote:'Initial, supported and independent work are kept separate. A facilitator enters rubric scores; the application does not infer learning improvement.',
 mapTitle:'The project map',mapIntro:'From one concrete lesson to operational choices and the evidence still needed.',
 map:[['Problem and product choices','MAT-01','Project brief','P03-CONTRACT','Product contract'],['Lesson and assessment','P03-ANCHOR','LES-02 design rationale','P03-ASSESS','Independent / delayed assessment'],['Research and limitations','P03-METHODS','Research methods appraisal','R01-GAPS','Evidence gaps'],['Rehearsal and responsibilities','P03-REHEARSE','Rehearsal protocol','P03-DATA','Participants and data']],
 ready:'Available for local review',available:'VI/EN interface, three draft lessons, a 54-document library with English counterparts, structured observations, readiness records and exports. Learning workflows use fictional data and AI fixture responses.',
 pending:'Decisions to make together',pendingText:'Choose the first families, the problem to solve, educational reviewers and data responsibilities. Willingness to pay, independent rehearsal outcomes and learner effectiveness have not been established.',feedbackAction:'Record your feedback',
 download:'Take the project kit with you',downloadIntro:'The package includes the application, VI/EN materials, research metadata and offline benchmark templates. Third-party full texts are excluded; references retain their external source links.',zip:'Download the WEB02 kit from the website',manifest:'Inspect the hosted file list and SHA-256',source:'Browse the GitHub source',downloadNote:'Download links require the hosted web edition. If you opened an offline package, keep its original archive or return to the website. Clicking a link does not confirm that the file was saved; check your device.',
 guideTitle:'Take one complete tour.',guideIntro:'This route helps you understand the problem, inspect a concrete lesson and record what needs revision without the builder sitting beside you.',routeTitle:'Read in this order',route:[['MAT-01','Start with what is known','The brief separates sourced information, proposals and open decisions.'],['P03-CONTRACT','Choose the first problem','Inspect product options and the hypotheses still open.'],['MAT-04','Read LES-02','Follow the scenario, reference cards, fixture response and eight-step instructions.'],['P03-ANCHOR','Understand the design rationale','Inspect the objective and limits of the rubric, independent task and delayed assessment.'],['P03-REHEARSE','Prepare an adult rehearsal','See how another adult can run the workflow and record assistance, timing and incidents.'],['P03-METHODS','Compare with the research','Read the scope of the studies and what remains unverified in Vietnam.'],['M01-ROADMAP','Choose the next work','Use the roadmap and acceptance conditions to record priorities.']],
 tryTitle:'Try a complete session with fictional data',trySteps:['Open Learning group and choose LES-02, “Read the updated notice accurately”. Use a synthetic learner or add a fictional identifier.','Start a session. Record initial thinking, then open the AI fixture; try the error or timeout mode and retry if useful.','Complete source checking, revision, explanation and a new task without AI.','The facilitator enters a fictional reviewer name or ID, three rubric scores and a note. Open Reports to inspect the separate stages.','Open Rehearsal to record observations and remaining work. Export an application backup or rehearsal record to transfer devices.'],
 areasTitle:'The work areas',areas:[['group','Learning group'],['activity','Activity authoring and review'],['session','Practice session'],['reports','Practice records'],['library','Complete library'],['workbench','Readiness and observations']],
 localTitle:'Each visitor has a separate workspace.',localOnly:'Data belongs to the browser, device and web origin you are using; it does not synchronise between people. Changing host, port or profile opens a different store. Application backups contain learners, sessions and observations; feedback exports are separate records. Transfer files yourself through an agreed collaboration channel.',
 reviewTitle:'Feedback for the next decision',reviewIntro:'Record feedback on the project and lesson; your name is optional. Do not enter real learner information. Feedback is saved only on your device and is not sent to the project owner.',reviewScope:'A visitor draft, not approval, consent or a learning outcome.',
 fields:{name:['Your name or reviewer ID (optional)','You may leave this blank.'],problem:['The problem to solve','What is happening in families? What is unclear or incorrectly framed?'],product:['Product choices','Which format is worth testing first, and why?'],lesson:['LES-02 wording and design','What is clear, misleading or in need of educational review?'],operations:['Operations and experience','Which steps, devices, backups or instructions need revision?'],next:['Decisions and next work','What priorities need agreement? Who should take part, and what evidence is missing?']},
 draftHint:'Your entries save in this browser as you type.',saved:'Feedback saved in this browser.',empty:'No feedback recorded.',exportMarkdown:'Export feedback Markdown',exportJSON:'Export feedback JSON',reviewReadError:'The saved feedback could not be read. Its original data is preserved; this draft is in memory only. Export it before closing.',reviewSaveError:'The browser could not save your feedback. Your draft remains in memory; export it before closing.',reviewExportNote:'This export contains feedback only. It does not replace an application backup. Feedback import and automatic sending are not implemented.',routeError:'This link is invalid or the document was not found. Open the complete library to choose a document.',copyLink:'Share document link',linkExport:'Shareable document link'
 }
};
export function renderOverview(locale){const c=COPY[locale];return `<section class="project-opening"><div class="project-lead"><h1>${c.title}</h1><p class="project-intro">${c.intro}</p><div class="project-entry"><a class="primary-link" href="#guide">${c.start}</a>${docs('MAT-04',c.lessonAction,locale)}<a href="#library">${c.libraryAction}</a></div><p class="project-scope">${c.scope}</p></div><aside class="project-example"><div class="invitation-paper"><span>${locale==='en'?'LES-02 / authored scenario':'LES-02 / tình huống tự soạn'}</span><h2>${c.exampleTitle}</h2><div class="invitation-change"><p>${locale==='en'?'Notice A':'Thông báo A'}<strong>09:00 · ${locale==='en'?'Wood room':'phòng Gỗ'}</strong></p><span aria-hidden="true">↳</span><p>${locale==='en'?'Updated notice B':'Thông báo B cập nhật'}<strong>09:30 · ${locale==='en'?'Paper room':'phòng Giấy'}</strong></p></div></div><p>${c.example}</p>${docs('P03-ANCHOR',c.design,locale)}<p><a class="secondary-link" href="#group?lesson=LES-02&lang=${locale}">${locale==='en'?'Try the LES-02 workflow':'Thử bài Đọc đúng lời hẹn'}</a></p><p class="small muted">${c.exampleNote}</p></aside></section><section class="project-section"><h2>${c.eight}</h2><ol class="learning-sequence">${c.steps.map(label=>`<li>${label}</li>`).join('')}</ol><p class="muted">${c.stepsNote}</p></section><section class="project-section"><h2>${c.mapTitle}</h2><p>${c.mapIntro}</p><div class="project-map">${c.map.map(([title,id,label,id2,label2])=>`<article><h3>${title}</h3><p>${docs(id,label,locale)}<br>${docs(id2,label2,locale)}</p></article>`).join('')}</div></section><section class="project-section project-choices"><div><h2>${c.ready}</h2><p>${c.available}</p></div><div><h2>${c.pending}</h2><p>${c.pendingText}</p><a href="#review">${c.feedbackAction}</a></div></section>${renderDownloads(locale)}`;}
export function renderDownloads(locale){const c=COPY[locale];return `<section class="project-section download-section"><h2>${c.download}</h2><p>${c.downloadIntro}</p><div class="actions"><a class="secondary-link" href="https://thuy-anh-ai-learning.vercel.app/downloads/project-review-WEB02.zip" target="_blank" rel="noopener">${c.zip}</a><a href="https://thuy-anh-ai-learning.vercel.app/downloads/project-review-WEB02.json" target="_blank" rel="noopener">${c.manifest}</a><a href="https://github.com/nclamvn/thuy-anh-ai-learning" target="_blank" rel="noopener">${c.source}</a></div><p class="small muted">${c.downloadNote}</p></section>`;}
export function renderGuide(locale){const c=COPY[locale];return `<div class="page-heading"><div><h1>${c.guideTitle}</h1><p class="page-intro">${c.guideIntro}</p></div><a class="secondary-link" href="#review">${c.feedbackAction}</a></div><section class="project-section"><h2>${c.routeTitle}</h2><ol class="review-route">${c.route.map(([id,label,detail])=>`<li><h3>${docs(id,label,locale)}</h3><p>${detail}</p><small>${id}</small></li>`).join('')}</ol></section><section class="project-section"><h2>${c.tryTitle}</h2><ol class="rehearsal-route">${c.trySteps.map(text=>`<li>${text}</li>`).join('')}</ol><a class="primary-link" href="#group?lesson=LES-02&lang=${locale}">${locale==='en'?'Try the LES-02 workflow':'Thử bài Đọc đúng lời hẹn'}</a></section><section class="project-section"><h2>${c.areasTitle}</h2><div class="area-links">${c.areas.map(([view,label])=>`<a href="#${view}">${label}</a>`).join('')}</div></section><section class="project-section"><h2>${c.localTitle}</h2><p>${c.localOnly}</p><a href="#review">${c.feedbackAction}</a></section>${renderDownloads(locale)}`;}
export function renderReview(locale,review,error=null,saved=false){const c=COPY[locale];return `<div class="page-heading"><div><h1>${c.reviewTitle}</h1><p class="page-intro">${c.reviewIntro}</p></div><a href="#guide" class="secondary-link">${c.guide}</a></div><form id="visitor-review" class="visitor-review" novalidate>${REVIEW_FIELDS.map(field=>`<div class="field"><label for="feedback-${field}">${c.fields[field][0]}</label>${field==='name'?`<input id="feedback-${field}" name="${field}" value="${E(review[field])}" maxlength="200" autocomplete="off">`:`<textarea id="feedback-${field}" name="${field}" maxlength="4000">${E(review[field])}</textarea>`}<p class="field-help">${c.fields[field][1]}</p></div>`).join('')}<p id="review-save-status" role="status" class="${error?'form-error':'small muted'}">${error?c[error==='review-read-error'||error==='review-protected'?'reviewReadError':'reviewSaveError']:(saved?c.saved:c.draftHint)}</p><div class="actions"><button type="button" id="export-review-md" class="secondary">${c.exportMarkdown}</button><button type="button" id="export-review-json" class="secondary">${c.exportJSON}</button></div><p class="small muted">${c.reviewScope} ${c.reviewExportNote}</p></form><section class="project-section"><h2>${c.localTitle}</h2><p>${c.localOnly}</p></section>`;}
