// Public authored paraphrases only; this module never reads or writes learning records.
export const SOURCE_SHA='3cc7fee4c0f745100b110155fdc4bceca434f526cdd143ccc49704c048811b8f';
export const REFERENCE_IDS=['R02-01','R02-02','R02-03','R02-04','R02-06','R02-07','R02-08',...Array.from({length:7},(_,i)=>`R03-0${i+1}`)];
const E=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const L=(v,l)=>v?.[l]??'';
export const TYPES={survey:['Khảo sát','Survey'],literacy_guide:['Hướng dẫn AI literacy','AI literacy guide'],qualitative_study:['Nghiên cứu định tính','Qualitative study'],country_note:['Báo cáo quốc gia PISA','PISA country note'],randomized_trial_working_paper:['Thử nghiệm ngẫu nhiên · working paper','Randomized trial · working paper'],research_synthesis:['Tổng hợp nghiên cứu','Research synthesis'],policy_context:['Bối cảnh chính sách','Policy context'],country_readiness_assessment:['Đánh giá mức sẵn sàng quốc gia','Country readiness assessment']};
export const COUNTRIES={US:['Hoa Kỳ','United States'],CA:['Canada','Canada'],VN:['Việt Nam','Viet Nam'],UK:['Vương quốc Anh','United Kingdom'],NG:['Nigeria','Nigeria'],MULTI:['Nhiều quốc gia','Multiple countries'],INTERNATIONAL:['Quốc tế','International'],UNSPECIFIED:['Không xác định','Unspecified']};
export const THEMES={family:['Gia đình và trải nghiệm AI','Families and AI experiences'],learning:['Học tập và năng lực tự làm','Learning and independent capability'],guidance:['Hướng dẫn sử dụng','Use guidance'],relationship:['Quan hệ và AI companion','Relationships and AI companions'],policy:['Chính sách và điều kiện triển khai','Policy and implementation conditions']};
export const countryKey=v=>({Canada:'CA','Viet Nam':'VN',Vietnam:'VN','Việt Nam':'VN','United Kingdom':'UK',Nigeria:'NG',International:'INTERNATIONAL'}[v]??v);
export const themeKey=c=>c.batch?.startsWith('R03')?({'R03-01':'learning','R03-02':'family','R03-03':'family','R03-04':'learning','R03-05':'learning','R03-06':'policy','R03-07':'policy'}[c.id]):c.scope;
export function safePublication(value){const url=new URL(value);if(url.protocol!=='https:'||url.username||url.password)throw Error('unsafe-reference-url');return url.href;}
export function reportLink(locale,id=null){if(!['vi','en'].includes(locale)||(id!==null&&!REFERENCE_IDS.includes(id)))throw Error('invalid-reference-link');return `references/report.html?lang=${locale}${id?'#source-'+id:''}`;}
export function referenceHash(id,locale){reportLink(locale,id);return `#references?doc=${id}&lang=${locale}`;}
const bilingual=v=>v&&typeof v.vi==='string'&&typeof v.en==='string'&&v.vi.length>0&&v.en.length>0;
export function validateReferenceCatalog(data){
 if(!data||data.schemaVersion!==1||data.kind!=='public-authored-reference-metadata'||data.sourceHTMLSha256!==SOURCE_SHA||data.reportHref!=='references/report.html'||!/^[a-f0-9]{64}$/.test(data.reportSha256)||data.documents!==14||data.claimReferences!==92||data.meta?.r03Claims!==57||data.meta?.r03SourceStatus!=='ACCEPTED_FOR_TRACEABILITY_SCOPE'||data.meta?.r03Final!==true||data.meta?.sourceReports!==14||!Array.isArray(data.cards)||data.cards.length!==14||data.cards.map(c=>c.id).join()!==REFERENCE_IDS.join())throw Error('invalid-reference-catalog');
 const claims=new Set();
 for(const c of data.cards){safePublication(c.url);if(!bilingual(c.title)||!TYPES[c.type]||!THEMES[themeKey(c)]||!Array.isArray(c.countries)||!c.countries.length||c.countries.some(v=>!COUNTRIES[countryKey(v)])||![c.population,c.method].every(v=>v===null||bilingual(v))||!Array.isArray(c.findings)||!c.findings.length||!c.findings.every(v=>bilingual(v)&&Array.isArray(v.claimIDs))||!Array.isArray(c.limitations)||!c.limitations.length||!c.limitations.every(bilingual)||!bilingual(c.implication)||c.implication.status!=='AI_PROPOSAL'||!c.date||!c.provenance||!Array.isArray(c.provenance.claimIDs)||c.provenance.claimIDs.length!==data.meta.sourceClaims[c.id])throw Error('invalid-reference-card');for(const id of c.provenance.claimIDs){if(typeof id!=='string'||claims.has(id))throw Error('invalid-reference-claims');claims.add(id);}if(c.findings.some(f=>f.claimIDs.some(id=>!c.provenance.claimIDs.includes(id))))throw Error('invalid-reference-claim-owner');}
 if(claims.size!==92)throw Error('invalid-reference-count');return data;
}
export async function fetchReferenceCatalog(fetcher=fetch){const response=await fetcher('./references/catalog.json');if(!response.ok)throw Error('reference-load-error');const text=await response.text();if(text.length>500000)throw Error('reference-catalog-too-large');return validateReferenceCatalog(JSON.parse(text));}
export function filterReferences(cards,{query='',type='',theme='',country=''}={}){const needle=query.normalize('NFD').replace(/\p{Diacritic}/gu,'').toLocaleLowerCase();return cards.filter(c=>(!type||c.type===type)&&(!theme||themeKey(c)===theme)&&(!country||c.countries.some(v=>countryKey(v)===country))&&JSON.stringify([c.id,c.title,c.publisher,c.population,c.method,c.findings,c.limitations,c.provenance.claimIDs,c.date]).normalize('NFD').replace(/\p{Diacritic}/gu,'').toLocaleLowerCase().includes(needle));}
export function parseReferenceRoute(hash){const [view,query,...extra]=String(hash).replace(/^#/,'').split('?');const params=new URLSearchParams(query??'');if(view!=='references'||extra.length||[...params.keys()].some(k=>!['doc','lang'].includes(k)||params.getAll(k).length!==1))return {doc:null,lang:null,error:'invalid-route'};const doc=params.get('doc'),lang=params.get('lang');if((doc!==null&&!/^[A-Z0-9][A-Z0-9_-]{1,99}$/.test(doc))||(lang!==null&&!['vi','en'].includes(lang)))return {doc:null,lang:null,error:'invalid-route'};return {doc,lang,error:null};}
export function referenceDate(value,locale){if(!value)return '';const phrases={'Ended early 2025':['Kết thúc đầu năm 2025','Ended early 2025'],'Multipleunderlyingstudies':['Nhiều nghiên cứu thành phần','Multiple underlying studies'],'Assessment since 2024-08':['Đánh giá từ 08/2024','Assessment since August 2024'],'2026(report)':['2026 (báo cáo)','2026 (report)']};if(phrases[value])return phrases[value][locale==='en'?1:0];if(value.startsWith('Captured '))return (locale==='en'?'Captured ':'Đã lưu nguồn ngày ')+value.slice(9);return value.replace(' to ',' – ');}
const COPY={vi:{title:'Đọc nguồn, hiểu giới hạn.',intro:'Những tài liệu giúp đặt câu hỏi tốt hơn về việc trẻ học cùng AI. Mỗi nguồn giữ rõ ai được nghiên cứu, cách nghiên cứu và điều chưa thể kết luận.',scope:'14 tài liệu R02/R03, 92 tham chiếu claim. Đây là tập nguồn đã tinh lọc, không phải toàn bộ nghiên cứu hay 14 thử nghiệm độc lập. Truy vết đã được kiểm; hiệu quả giáo dục và nhu cầu gia đình vẫn cần xác nhận.',full:'Đọc hồ sơ nghiên cứu đầy đủ',library:'Về thư viện học liệu',search:'Tìm trong cả hai ngôn ngữ',type:'Loại tài liệu',theme:'Phạm vi câu hỏi',country:'Quốc gia',all:'Tất cả',reset:'Xóa bộ lọc',results:'tài liệu phù hợp',empty:'Không có nguồn phù hợp. Thử từ khóa khác hoặc xóa bộ lọc.',loading:'Đang đọc danh mục nguồn…',error:'Chưa đọc được danh mục nguồn. Các tài liệu đã có vẫn nằm trong hồ sơ đầy đủ.',retry:'Đọc lại danh mục',unknown:'Không tìm thấy mã nguồn trong liên kết. Bạn có thể chọn một nguồn bên dưới.',population:'Đối tượng và mẫu',method:'Phương pháp',finding:'Điều nguồn nêu',limit:'Giới hạn áp dụng',proposal:'Gợi ý cho dự án · đề xuất AI',primary:'Mở nguồn xuất bản',section:'Đọc mục này trong hồ sơ',share:'Liên kết riêng của nguồn',date:'Ngày công bố',fieldwork:'Thời gian thu thập dữ liệu',version:'Phiên bản',unknownValue:'Chưa xác định trong metadata đã tinh lọc.',more:'Đọc phương pháp, kết quả và giới hạn',trace:'Phạm vi chấp nhận: truy vết nguồn. Không thay việc rà soát sư phạm hoặc quyết định của Thuý Anh.'},en:{title:'Read the source. Understand its limits.',intro:'Documents that help us ask better questions about children learning with AI. Each source keeps its population, method and limits visible.',scope:'14 R02/R03 documents, 92 claim references. This is a curated corpus, neither a census of research nor 14 independent trials. Source traceability has been checked; educational effectiveness and family demand remain unvalidated.',full:'Read the full research dossier',library:'Return to the materials library',search:'Search both languages',type:'Document type',theme:'Question theme',country:'Country',all:'All',reset:'Clear filters',results:'matching documents',empty:'No matching source. Try another term or clear the filters.',loading:'Loading the source ledger…',error:'The source ledger could not be loaded. The full dossier remains available.',retry:'Reload the ledger',unknown:'The linked source ID was not found. Choose a source below.',population:'Population and sample',method:'Method',finding:'What the source reports',limit:'Limits of application',proposal:'Project implication · AI proposal',primary:'Open primary publication',section:'Read this section in the dossier',share:'Source permalink',date:'Publication date',fieldwork:'Fieldwork',version:'Version',unknownValue:'Not established in the curated metadata.',more:'Read methods, findings and limitations',trace:'Acceptance scope: source traceability. This does not replace educational review or Thuý Anh’s decision.'}};
export function renderReferences(locale,data,filters={},selected=null,status=''){
 const c=COPY[locale]??COPY.vi,n=locale==='en'?1:0,cards=data?.cards??[];const options=(map,key)=>Object.entries(map).filter(([v])=>cards.some(s=>key==='type'?s.type===v:key==='theme'?themeKey(s)===v:s.countries.some(country=>countryKey(country)===v))).map(([v,label])=>`<option value="${E(v)}" ${filters[key]===v?'selected':''}>${E(label[n])}</option>`).join('');
 return `<section class="reference-room"><header class="reference-opening"><div><h1>${c.title}</h1><p>${c.intro}</p><a class="secondary-link" href="${reportLink(locale)}">${c.full}</a></div><img src="./assets/brandmark.svg" width="130" height="125" alt=""></header><p class="reference-scope">${c.scope}</p><div class="reference-reading-plane"><aside class="reference-margin"><form id="reference-filters" role="search"><label for="reference-query">${c.search}</label><input id="reference-query" type="search" maxlength="200" value="${E(filters.query??'')}" autocomplete="off">${['type','theme','country'].map(key=>`<label for="reference-${key}">${c[key]}</label><select id="reference-${key}"><option value="">${c.all}</option>${options(key==='type'?TYPES:key==='theme'?THEMES:COUNTRIES,key)}</select>`).join('')}<button type="button" id="reference-reset" class="secondary">${c.reset}</button></form><a href="#library?lang=${locale}">${c.library}</a><p class="small">${c.trace}</p></aside><section class="reference-ledger" aria-label="${E(c.title)}">${renderReferenceLedger(locale,data,filters,selected,status)}</section></div></section>`;
}

export function renderReferenceLedger(locale,data,filters={},selected=null,status=''){const c=COPY[locale]??COPY.vi,n=locale==='en'?1:0,matched=filterReferences(data?.cards??[],filters);return `<p id="reference-results" role="status">${data?`${matched.length} ${c.results}`:c.loading}</p>${status?`<p class="form-error" role="alert">${status==='unknown'?c.unknown:c.error}</p>${status==='error'?`<button id="reference-retry" class="secondary">${c.retry}</button>`:''}`:''}${matched.map(s=>`<article class="reference-entry" id="reference-${s.id}"><div class="reference-source-line"><span>${s.id}</span><span>${E(TYPES[s.type][n])}</span></div><h2>${E(L(s.title,locale))}</h2><p class="reference-publisher">${E(s.publisher)} · ${s.countries.map(v=>E(COUNTRIES[countryKey(v)][n])).join(', ')}</p><p>${E(L(s.findings[0],locale))}</p><details ${selected===s.id?'open':''}><summary>${c.more}</summary><dl>${[['population',c.population],['method',c.method]].map(([key,label])=>`<dt>${label}</dt><dd>${E(L(s[key],locale)||c.unknownValue)}</dd>`).join('')}${[['published',c.date],['fieldwork',c.fieldwork],['version',c.version]].map(([key,label])=>`<dt>${label}</dt><dd>${E(referenceDate(s.date[key],locale)||c.unknownValue)}</dd>`).join('')}</dl><h3>${c.finding}</h3><ul>${s.findings.map(f=>`<li>${E(L(f,locale))}</li>`).join('')}</ul><h3>${c.limit}</h3><ul>${s.limitations.map(f=>`<li>${E(L(f,locale))}</li>`).join('')}</ul><div class="reference-proposal"><h3>${c.proposal}</h3><p>${E(L(s.implication,locale))}</p></div></details><div class="reference-links"><a href="${E(safePublication(s.url))}" target="_blank" rel="noopener noreferrer">${c.primary}</a><a href="${reportLink(locale,s.id)}">${c.section}</a><a href="${referenceHash(s.id,locale)}">${c.share}</a></div></article>`).join('')}${data&&!matched.length?`<p>${c.empty}</p>`:''}`;}
