// UI05 room composition. Artwork is descriptive only; all status is supplied by records.
const E=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const ROOM_ROUTES=['group','activity','session','reports','workbench','library','guide','review'];
export function roomArt(route,cls=''){if(!ROOM_ROUTES.includes(route))throw Error('Unknown room');return `<figure class="room-art ${cls}" aria-hidden="true"><img src="assets/rooms/${route}.svg" alt="" width="640" height="360"></figure>`;}
export function roomOpening(route,title,intro,extra=''){return `<header class="room-opening room-${route}"><div class="room-heading"><h1>${title}</h1><p class="page-intro">${intro}</p>${extra?`<div class="room-actions">${extra}</div>`:''}</div>${roomArt(route)}</header>`;}
export function learnerCrest(index){const forms=['M26 8 44 20 41 42 24 49 8 34 10 15Z','M27 8c24 0 24 40 0 40S3 8 27 8Z','m26 6 7 14 16 4-12 12 1 16-12-8-13 8 2-16L3 24l16-4Z'];return `<svg class="learner-crest" viewBox="0 0 54 56" aria-hidden="true"><path d="${forms[index%forms.length]}"/><path d="M17 31c5 6 14 7 21-2M19 23h1m14 0h1"/></svg>`;}
export function readinessLedger(keys,records,{labels,status,locale}){return `<ol class="condition-ledger">${keys.map((key,n)=>{const r=records.find(item=>item.key===key);return `<li class="condition-leaf ${r?.status==='ready-for-adult-rehearsal'?'evidence-recorded':''}"><div class="condition-number" aria-hidden="true">${n+1}</div><div><h3>${E(labels[key][locale==='en'?1:0])}</h3><p class="condition-status">${E(status(r?.status??'pending'))}</p>${r?`<p class="condition-owner">${E(r.owner)} / ${E(r.version)}</p><p class="condition-evidence">${E(r.note)}</p>`:`<p class="condition-evidence">${locale==='en'?'No owner or rationale recorded.':'Chưa ghi người phụ trách hoặc căn cứ.'}</p>`}<button type="button" class="text-button condition-edit" data-condition="${E(key)}">${locale==='en'?'Write in this record':'Ghi vào điều kiện này'}</button></div></li>`;}).join('')}</ol>`;}

export function roomHeading(route,title,intro,extra=''){if(!ROOM_ROUTES.includes(route))throw Error('Unknown room');return `<header class="workspace-heading heading-${route}"><div><h1>${title}</h1><p class="page-intro">${intro}</p></div>${extra?`<div class="workspace-actions">${extra}</div>`:''}</header>`;}
