// Shared browser/server contracts. Schema output is revalidated semantically, never executed.
import {analyzeStory} from './story.js';
import {BASE_SPEC,WORLD_KEYS,validateWorldSpec} from './world.js';
const clone=x=>JSON.parse(JSON.stringify(x));
const exact=(v,keys)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).length===keys.length&&keys.every(k=>Object.hasOwn(v,k));
const fail=code=>{throw Error(code);};
export const SNAPSHOT_LIMITS=Object.freeze({sourceText:3000,revisionText:1000,baseSourceText:3000,baseRevisionText:1000,mentorNotes:500,answerNote:300,importBytes:131072});
const SNAPSHOT_KEYS=['schemaVersion','generation','sourceText','revisionText','basePrintId','baseSourceText','baseRevisionText','baseWorld','ageBand','goals','mentorNotes','answerNotes'];
const PAIR={type:'object',additionalProperties:false,properties:{vi:{type:'string',maxLength:600},en:{type:'string',maxLength:600}},required:['vi','en']};
const QUOTE={type:'object',additionalProperties:false,properties:{source:{type:'string',enum:['sourceText','revisionText','baseSourceText','baseRevisionText','mentorNotes','answerNote0','answerNote1','answerNote2']},start:{type:'integer',minimum:0},end:{type:'integer',minimum:0},text:{type:'string',maxLength:3000}},required:['source','start','end','text']};
const TYPES={sky:{type:'string',enum:['sunset','night']},cityScale:{type:'number',minimum:.8,maximum:1.3},gardens:{type:'boolean'},starBridge:{type:'boolean'},whaleColor:{type:'string',enum:['indigo','teal']}};
export const PLANNER_SCHEMA={type:'object',additionalProperties:false,properties:{schemaVersion:{type:'integer',enum:[1]},inputBinding:{type:'string',maxLength:64000},reflection:PAIR,title:PAIR,proposals:{type:'object',additionalProperties:false,properties:Object.fromEntries(WORLD_KEYS.map(k=>[k,{type:'object',additionalProperties:false,properties:{value:TYPES[k],rationale:PAIR,evidence:{type:'array',maxItems:16,items:QUOTE}},required:['value','rationale','evidence']}])),required:[...WORLD_KEYS]},questions:{type:'array',maxItems:3,items:PAIR},unrendered:{type:'array',maxItems:16,items:{type:'object',additionalProperties:false,properties:{id:{type:'string',maxLength:64},required:{type:'boolean'},field:{type:['string','null'],enum:[null,...WORLD_KEYS]},reason:PAIR,evidence:{type:'array',maxItems:16,items:QUOTE}},required:['id','required','field','reason','evidence']}}},required:['schemaVersion','inputBinding','reflection','title','proposals','questions','unrendered']};
function bounded(value,max,empty=true){if(typeof value!=='string'||value.length>max||(!empty&&!value.trim()))fail('invalid-planner-text');return value;}
export function validatePlannerSnapshot(input){if(!exact(input,SNAPSHOT_KEYS)||input.schemaVersion!==1||!Number.isSafeInteger(input.generation)||input.generation<0)fail('invalid-snapshot');for(const k of ['sourceText','revisionText','baseSourceText','baseRevisionText','mentorNotes'])bounded(input[k],SNAPSHOT_LIMITS[k]);if(!input.sourceText.trim())fail('empty-source');if(input.basePrintId!==null&&(!Number.isSafeInteger(input.basePrintId)||input.basePrintId<1))fail('invalid-base');if(input.baseWorld!==null){const s=clone(BASE_SPEC);s.world=input.baseWorld;validateWorldSpec(s);if(input.basePrintId===null||!input.baseSourceText.trim())fail('invalid-base');}else if(input.basePrintId!==null||input.baseSourceText!==''||input.baseRevisionText!=='')fail('invalid-base');if(!['6-8','9-11','12-15'].includes(input.ageBand)||!Array.isArray(input.goals)||input.goals.length>3||new Set(input.goals).size!==input.goals.length||input.goals.some(g=>!['authorship','iteration','ai-literacy'].includes(g)))fail('invalid-facilitation');if(!Array.isArray(input.answerNotes)||input.answerNotes.length>3)fail('invalid-facilitation');input.answerNotes.forEach(x=>bounded(x,300));return clone(input);}
export function bindingFor(input){const s=validatePlannerSnapshot(input);return JSON.stringify(Object.fromEntries(SNAPSHOT_KEYS.map(k=>[k,k==='baseWorld'&&s[k]?Object.fromEntries(WORLD_KEYS.map(w=>[w,s[k][w]])):s[k]])));}
function cleanPair(p,max=600){if(!exact(p,['vi','en']))fail('invalid-planner-pair');for(const l of ['vi','en']){bounded(p[l],max,false);if(/https?:|javascript:|data:|<\/?[a-z][^>]*>|\b(?:eval|alert|fetch|Function)\s*\(|=>|\bimport\s+[{'*]/i.test(p[l]))fail('unsafe-planner-output');const normalized=p[l].normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d');if(/(?:em|ban|con) se tro thanh|sinh ra de|cam xuc cua|born (?:engineer|artist)|you will become|future career|diagnos|\bIQ\b|\bADHD\b|autis|chan doan|nghe tuong lai|thi[eê]n t[aà]i/i.test(normalized))fail('unsupported-personal-inference');}}
function quoteText(s,source){if(/^answerNote[012]$/.test(source))return s.answerNotes[Number(source.at(-1))];return ['sourceText','revisionText','baseSourceText','baseRevisionText','mentorNotes'].includes(source)?s[source]:undefined;}
function validateEvidence(list,s){if(!Array.isArray(list)||list.length>16)fail('invalid-evidence');for(const q of list){if(!exact(q,['source','start','end','text']))fail('invalid-evidence');const input=quoteText(s,q.source);if(typeof input!=='string'||!Number.isInteger(q.start)||!Number.isInteger(q.end)||q.start<0||q.end<=q.start||q.end>input.length||q.text!==input.slice(q.start,q.end))fail('invalid-evidence');}}
export function validatePlannerPlan(plan,input){if(new TextEncoder().encode(JSON.stringify(plan)).length>SNAPSHOT_LIMITS.importBytes)fail('planner-too-large');const s=validatePlannerSnapshot(input);if(!exact(plan,PLANNER_SCHEMA.required)||plan.schemaVersion!==1||plan.inputBinding!==bindingFor(s))fail('wrong-planner-binding');cleanPair(plan.reflection);cleanPair(plan.title,140);if(!exact(plan.proposals,WORLD_KEYS))fail('invalid-proposals');const spec=clone(BASE_SPEC);for(const k of WORLD_KEYS){const p=plan.proposals[k];if(!exact(p,['value','rationale','evidence']))fail('invalid-proposals');spec.world[k]=p.value;cleanPair(p.rationale,500);validateEvidence(p.evidence,s);}validateWorldSpec(spec);if(!Array.isArray(plan.questions)||plan.questions.length>3||!Array.isArray(plan.unrendered)||plan.unrendered.length>16)fail('invalid-planner-list');plan.questions.forEach(q=>cleanPair(q,200));const ids=new Set();for(const u of plan.unrendered){if(!exact(u,['id','required','field','reason','evidence'])||typeof u.id!=='string'||!/^[a-z0-9][a-z0-9-]{0,63}$/.test(u.id)||ids.has(u.id)||typeof u.required!=='boolean'||![null,...WORLD_KEYS].includes(u.field))fail('invalid-unrendered');ids.add(u.id);cleanPair(u.reason,500);validateEvidence(u.evidence,s);if(!u.evidence.length)fail('unrendered-without-source');}return clone(plan);}
export function preparedPlannerPlan(input){const s=validatePlannerSnapshot(input),prior=s.baseWorld?{...structuredClone(BASE_SPEC),world:s.baseWorld}:null,local=analyzeStory(s.sourceText,{priorSpec:prior,priorStory:{sourceText:s.baseSourceText,revisionText:s.baseRevisionText},priorPrintId:s.basePrintId,revisionText:s.revisionText,dataKind:'prepared-synthetic-demo'}),world=local.world;return validatePlannerPlan({schemaVersion:1,inputBinding:bindingFor(s),reflection:{vi:'Đây là đề xuất theo bộ đối chiếu từ khóa local có giới hạn. Hãy kiểm tra từng đoạn gốc và quyết định điều muốn giữ.',en:'This is a scripted proposal from the limited local keyword matcher. Check the original evidence and decide what to keep.'},title:{vi:'Bản thiết kế cá voi và thành phố',en:'Whale and city draft'},proposals:Object.fromEntries(WORLD_KEYS.map(k=>[k,{value:world[k],rationale:structuredClone(local.fieldEvidence[k].reason),evidence:local.fieldEvidence[k].quotes.filter(q=>['sourceText','revisionText'].includes(q.source)).map(q=>({source:q.source,start:q.start,end:q.end,text:q.text}))}])),questions:[{vi:'Bạn muốn giữ điều gì nhất trong ý tưởng của mình?',en:'What would you most like to keep in your idea?'},{vi:'Có điều gì bạn muốn sửa hoặc để lại cho lần sau?',en:'Is there anything you would change or keep for later?'}],unrendered:local.issues.slice(0,16).map(i=>({id:i.id,required:i.required,field:i.field,reason:i.message,evidence:i.evidence.filter(q=>['sourceText','revisionText'].includes(q.source)).slice(0,16).map(q=>({source:q.source,start:q.start,end:q.end,text:q.text}))})).filter(i=>i.evidence.length)},s);}
export function buildPlannerPrompt(input){const snapshot=validatePlannerSnapshot(input);return {kind:'adult-mediated-manual-planner-prompt',scope:'Prepared or session input; no authenticated child authorship. Manual evaluation, not live success.',instructions:'Return only PlannerPlan JSON under the supplied schema. Reflect without inventing child words. This template ONLY renders a flying whale carrying a city. Propose five bounded options with rationale; quote exact UTF-16 slices from the named input only. Defaults/suggestions may have empty evidence. Keep unsupported/invariant/conflicting wishes unrendered; do not claim fulfilment. Up to three open, nonleading questions; no diagnoses, personality, emotion, aptitude or career inference. Never include URLs, executable code, HTML, assets, or provider credentials. inputBinding must equal the exact supplied binding.',inputBinding:bindingFor(snapshot),snapshot,schema:clone(PLANNER_SCHEMA)};}
