// Limited deterministic VI/EN signal matcher. No model, network, storage or arbitrary code.
import {validatePlannerSnapshot,validatePlannerPlan,bindingFor} from './planner.js';
import {BASE_SPEC,WORLD_KEYS,validateWorldSpec,worldDiff,createWorldSession} from './world.js';
const clone=v=>JSON.parse(JSON.stringify(v));
export const LIMITS=Object.freeze({story:3000,revision:1000,title:140,summary:600});
export const ANALYZER_LABEL={vi:'Bộ đối chiếu từ khóa local có giới hạn; không phải AI trực tiếp.',en:'Limited local keyword matcher; no live AI or arbitrary-story understanding.'};
const pair=(vi,en)=>({vi,en});
const text=(v,max,empty=true)=>{if(typeof v!=='string'||v.length>max||(!empty&&!v.trim()))throw Error('invalid-text');return v;};
function mapped(input){let value='',map=[],end=[],offset=0;for(const char of input){const n=char.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/đ/g,'d');for(let i=0;i<n.length;i++){map.push(offset);end.push(offset+char.length);}if(!n&&end.length)end[end.length-1]=offset+char.length;value+=n;offset+=char.length;}return {value,map,end};}
function quote(input,m,start,length,source){const a=m.map[start]??0,b=m.end[start+length-1]??a;return {text:input.slice(a,b),start:a,end:b,source};}
const SIGNALS={sky:[['night',/\b(?:ban dem|troi dem|dem|night|nighttime)\b/g],['sunset',/\b(?:hoang hon|sunset|dusk)\b/g]],gardens:[[true,/\b(?:khu vuon|vuon|garden|gardens)\b/g]],starBridge:[[true,/\b(?:cay cau (?:bang )?sao|cau (?:bang )?sao|star bridge|bridge of stars)\b/g]],whaleColor:[['teal',/\b(?:xanh ngoc|xanh luc lam|teal)\b/g],['indigo',/\b(?:xanh cham|indigo)\b/g]],cityScale:[[.8,/\b(?:thanh pho (?:rat )?nho|tiny city|small city)\b/g],[1.3,/\b(?:thanh pho (?:rat )?lon|large city|big city)\b/g]]};
const NEG=/\b(?:khong(?: co| muon| can)?|khong them|dung(?: co| them)?|bo|xoa|without|no|remove|not|do not (?:want|add)|don't (?:want|add))\s+(?:(?:mot|cac|nhung|the|a|any|small|khu|cay)\s+){0,3}$/;
const FILLER=new Set(('con muon mot ca voi mau bay cho thanh pho cua minh toi em co va nhung cac khu cay bang la tren lung nho lon rat ban troi dem hoang hon vung voi ngoi them khong bo xoa giu nguyen nhung chi lai di thanh doi sang at to from change keep the a an with and but carries carrying carry on its back is of want i my flying whale city small tiny large big in at has no without remove garden gardens star bridge stars sunset night nighttime dusk teal indigo colour color add vao khi doi xanh ngoc cham luc lam ma minh them can co bay vua both').split(/\s+/));
function issue(id,kind,field,required,message,evidence=[]){return {id,kind,field,required,message,evidence,resolved:false};}
function emptyDraft(sourceText='',dataKind='local-session-story'){const world=clone(BASE_SPEC.world);return {sourceText,sourceKind:dataKind,revisionText:'',revisionKind:null,title:'',summary:'',metadata:{titleOrigin:'none',titleRetained:false,narrationMode:'none',narrationOrigin:'none',narrationRetained:false},world,fieldEvidence:Object.fromEntries(WORLD_KEYS.map(k=>[k,{value:world[k],origin:'offline-suggestion',quotes:[],reason:pair('Mặc định đề xuất, chưa có lời kể xác nhận.','Proposed default; not quoted from the story.'),status:'default-proposal'}])),issues:[],acknowledgements:{},mode:'new',dataKind,analyzed:false,revisionPending:false,analyzerLabel:clone(ANALYZER_LABEL),basePrintId:null};}
export function artworkNarration(draft){return draft?.metadata?.narrationMode==='original'?draft.sourceText:draft?.metadata?.narrationMode==='edited'?draft.summary:'';}
function carryMetadata(next,previous,sourceChanged=false){if(!previous)return next;next.title=previous.title??'';next.summary=previous.summary??'';next.metadata=clone(previous.metadata??{titleOrigin:next.title?'manual-session':'none',titleRetained:false,narrationMode:next.summary?'edited':'none',narrationOrigin:next.summary?'manual-session':'none',narrationRetained:false});if(sourceChanged){next.metadata.titleRetained=next.metadata.titleOrigin==='manual-session';next.metadata.narrationRetained=next.metadata.narrationMode==='edited';}return next;}
function priorQuotes(evidence,priorStory,printId){return (evidence?.quotes||[]).map(q=>{const carried=q.source==='prior-print',sourceField=carried?q.sourceField:q.source,sourceTextSnapshot=carried?q.sourceTextSnapshot:(q.sourceTextSnapshot??(priorStory?.[sourceField]??priorStory?.plannerSnapshot?.[sourceField]??(/^answerNote[012]$/.test(sourceField)?priorStory?.plannerSnapshot?.answerNotes?.[Number(sourceField.at(-1))]:undefined))),id=carried?q.printId:printId;if(!['sourceText','revisionText','baseSourceText','baseRevisionText','mentorNotes','answerNote0','answerNote1','answerNote2'].includes(sourceField)||typeof sourceTextSnapshot!=='string'||sourceTextSnapshot.length>LIMITS.story||!Number.isInteger(q.start)||!Number.isInteger(q.end)||q.start<0||q.end<q.start||q.end>sourceTextSnapshot.length||q.text!==sourceTextSnapshot.slice(q.start,q.end)||!Number.isInteger(id)||id<1)throw Error('invalid-prior-evidence');return {...clone(q),source:'prior-print',sourceField,sourceTextSnapshot,printId:id};});}
export function analyzeStory(sourceText,{priorSpec=null,priorStory=null,priorPrintId=null,revisionText='',dataKind='local-session-story'}={}){
 text(sourceText,LIMITS.story,false);text(revisionText,LIMITS.revision);if(!['local-session-story','prepared-synthetic-demo'].includes(dataKind))throw Error('invalid-kind');
 const draft=emptyDraft(sourceText,dataKind),prior=priorSpec?validateWorldSpec(priorSpec):null;draft.analyzed=true;draft.mode=prior?'revision':'new';draft.revisionText=revisionText;draft.revisionKind=revisionText?'local-session-story':null;draft.basePrintId=priorPrintId;
 if(prior){for(const old of priorStory?.blueprint?.issues||[]){if(!old.required&&!old.resolved){draft.issues.push({...clone(old),evidence:priorQuotes({quotes:old.evidence},priorStory,priorPrintId)});if(priorStory.blueprint.acknowledgements?.[old.id]===true)draft.acknowledgements[old.id]=true;}}draft.world=clone(prior.world);for(const key of WORLD_KEYS){const old=priorStory?.fieldEvidence?.[key];draft.fieldEvidence[key]={value:prior.world[key],origin:old?.origin||'offline-suggestion',quotes:priorQuotes(old,priorStory,priorPrintId),reason:pair('Giữ từ bản đã in; yêu cầu sửa không đổi lựa chọn này.','Retained from the printed snapshot; this revision does not change it.'),status:'retained-prior'};}}
 const carriedCount=draft.issues.length;
 const input=prior?revisionText:sourceText,source=prior?'revisionText':'sourceText',m=mapped(input),recognized=[];
 function hits(regex){return [...m.value.matchAll(regex)].map(x=>({start:x.index,length:x[0].length,text:x[0],q:quote(input,m,x.index,x[0].length,source)}));}
 const whale=hits(/\b(?:ca voi|whale)\b/g),city=hits(/\b(?:thanh pho|city)\b/g);recognized.push(...whale,...city,...hits(/\b(?:bay|flying)\b/g));
 const invariantRemoval=/\b(?:bo|xoa|khong (?:co|can|muon)|do not want|don't want|remove|without|not|no)\s+(?:(?:mot|the|a|flying|bay)\s+){0,2}(?:ca voi|whale|thanh pho|city)\b/;
 const ground=/\b(?:mat dat|tren dat|on the ground|grounded|cannot fly|khong bay)\b/;
 const alternate=hits(/\b(?:con rong|rong|dragon|unicorn|ky lan|spaceship|tau vu tru|dolphin|ca heo|elephant|voi|cat|con meo|robot)\b/g).filter(h=>!whale.some(w=>h.start>=w.start&&h.start<w.start+w.length));
 if(invariantRemoval.test(m.value)||ground.test(m.value))draft.issues.push(issue('invariant-change','invariant',null,true,pair('Yêu cầu bỏ hoặc đổi điều bất biến. Hãy sửa lời kể; bản này cần cá voi bay mang thành phố.','The request removes an invariant. Revise it: this template requires a flying whale carrying a city.'),[quote(input,m,0,m.value.length,source)]));
 if(!prior&&(!whale.length||!city.length))draft.issues.push(issue('world-scope','unsupported-world',null,true,pair('Chưa xác nhận rõ cá voi và thành phố; không tự thay ý tưởng khác bằng mẫu cá voi.','Whale and city intent is not explicit; another idea will not be silently replaced with this template.'),[quote(input,m,0,m.value.length,source)]));
 if(alternate.length){const required=!whale.length||/\b(?:instead|rather than|thay|doi (?:ca voi|whale)|replace)\b/.test(m.value);draft.issues.push(issue('alternate-creature','unsupported-world',null,required,pair('Nhân vật/phương tiện khác nằm ngoài mẫu; chưa được dựng.','Another creature/vehicle is outside this template and is not rendered.'),alternate.map(h=>h.q)));recognized.push(...alternate);}
 for(const key of WORLD_KEYS){let found=[];for(const [value,regex] of SIGNALS[key])for(const h of hits(regex)){const prefixStart=Math.max(0,h.start-65),prefix=m.value.slice(prefixStart,h.start),double=/\b(?:do not remove|don't remove|not remove|khong bo|dung bo|dung xoa)\s+(?:(?:mot|the|a|khu|cay)\s+){0,3}$/.exec(prefix),negative=NEG.exec(prefix);let signal=h;recognized.push(h);if(double){const start=prefixStart+double.index,q=quote(input,m,start,h.start+h.length-start,source);recognized.push({start,length:h.start+h.length-start});draft.issues.push(issue('ambiguous-negation-'+key,'unknown',key,true,pair('Phủ định việc bỏ một lựa chọn cần được xác định lại; chưa tự đổi giá trị.','Negated removal needs an explicit choice; the value is not changed automatically.'),[q]));continue;}const neg=!!negative;if(negative){const start=prefixStart+negative.index;signal={...h,q:quote(input,m,start,h.start+h.length-start,source)};recognized.push({start,length:h.start+h.length-start});}if(typeof value==='boolean')found.push({...signal,value:!neg});else if(!neg)found.push({...signal,value});else draft.issues.push(issue('negated-'+key,'unknown',key,true,pair('Giá trị được phủ định; cần chọn rõ một phương án được hỗ trợ.','A supported value was negated; choose a supported alternative explicitly.'),[signal.q]));}
  if(key==='sky'&&found.length>1){const targeted=found.filter(h=>/\b(?:to|sang|thanh)\s*$/.test(m.value.slice(Math.max(0,h.start-20),h.start)));if(targeted.length===1)found=targeted;}
  const unsupported=key==='sky'?hits(/\b(?:rainy|rain|daytime|sunrise|binh minh|ban ngay|troi mua)\b/g):key==='whaleColor'?hits(/\b(?:red|pink|yellow|purple|mau do|mau hong|mau vang|mau tim)\b/g):[];if(unsupported.length)draft.issues.push(issue('unsupported-'+key,'unknown',key,true,pair('Giá trị ngoài bộ lựa chọn được hỗ trợ; hãy chọn rõ phương án trước khi in.','Value outside supported choices; select an explicit supported alternative before printing.'),unsupported.map(h=>h.q)));
  const values=[...new Set(found.map(h=>h.value))];if(values.length>1){draft.issues.push(issue('conflict-'+key,'conflict',key,true,pair('Có lựa chọn mâu thuẫn. Hãy chọn lại trường này trước khi in.','Conflicting choices: choose this field explicitly before printing.'),found.map(h=>h.q)));draft.fieldEvidence[key]={value:draft.world[key],origin:'offline-suggestion',quotes:found.map(h=>h.q),reason:pair('Chưa phân xử mâu thuẫn.','Conflict unresolved.'),status:'default-proposal'};}
  else if(values.length===1){draft.world[key]=values[0];draft.fieldEvidence[key]={value:values[0],origin:dataKind==='prepared-synthetic-demo'&&!prior?'offline-suggestion':'session-input',quotes:found.map(h=>h.q),reason:pair('Tín hiệu từ khóa có đoạn gốc; chưa phải hiểu toàn bộ câu chuyện.','Keyword evidence only; not full-story understanding.'),status:'extracted'};}
 }
 // Any remaining meaningful words become an explicit unmet item; no silent coverage claim.
 let remaining=m.value.split('');for(const h of recognized)for(let i=h.start;i<h.start+h.length;i++)remaining[i]=' ';
 const unknown=[...remaining.join('').matchAll(/[a-z0-9]+/g)].filter(x=>!FILLER.has(x[0])).map(x=>quote(input,m,x.index,x[0].length,source));
 if(unknown.length){const words=[...new Set(unknown.map(q=>q.text))].slice(0,16);draft.issues.push(issue('unmatched-details','unmet',null,false,pair('Chi tiết chưa được dựng: '+words.join(', ')+'. Chỉ xác nhận bỏ qua, không coi là đã thực hiện.','Details not rendered: '+words.join(', ')+'. Acknowledge omission, not fulfilment.'),[quote(input,m,0,m.value.length,source)]));}
 // New revision issues have distinct IDs; prior omission acknowledgements keep their provenance.
 if(prior)for(const i of draft.issues.slice(carriedCount))i.id+='-revision-'+priorPrintId;
 // A repeated negated signal produces one blocker per field, with all evidence retained.
 const unique=new Map();for(const i of draft.issues){if(unique.has(i.id))unique.get(i.id).evidence.push(...i.evidence);else unique.set(i.id,i);}draft.issues=[...unique.values()];
 for(const e of Object.values(draft.fieldEvidence))e.quotes=e.quotes.slice(0,16);
 if(draft.issues.length>64)throw Error('too-many-issues');

 return draft;
}
function blockers(draft){if(!draft.analyzed)return [issue('not-analyzed','workflow',null,true,pair('Hãy phản hồi/đối chiếu lời kể trước.','Reflect/analyze the story first.'))];if(draft.revisionPending)return [issue('revision-pending','workflow',null,true,pair('Yêu cầu sửa mới chưa được phản hồi.','Review the new revision request first.'))];return draft.issues.filter(i=>!i.resolved&&(i.required||draft.acknowledgements[i.id]!==true));}
export function createStorySession({compile,dispose=()=>{},initialSpec=BASE_SPEC,initialArtifact=null}={}){
 const world=createWorldSession(compile,dispose,{initialSpec,initialArtifact});let revision=0,draft=emptyDraft(),confirmation=null,printed={spec:world.spec,story:null,unmetDetails:[],confirmedInSession:false,dataKind:'prepared-synthetic-demo',printId:0},history=[],plannerRequest=null,plannerPreview=null;
 function invalidate(){revision++;confirmation=null;plannerRequest=null;plannerPreview=null;}
 function getDraft(){return {...clone(draft),revision};}
 function specFromDraft(){const next=world.spec;next.dataKind=draft.dataKind;next.world=clone(draft.world);const changed=worldDiff(world.spec,next).length>0;next.version=world.spec.version+(changed?1:0);next.choices=WORLD_KEYS.map(key=>({id:key.replace(/[A-Z]/g,c=>'-'+c.toLowerCase()),description:pair(key+': '+String(draft.world[key])+' · xác nhận trong phiên, không xác thực trẻ.',key+': '+String(draft.world[key])+' · in-session confirmation, not child authentication.'),origin:draft.fieldEvidence[key].origin,status:'confirmed-in-session'}));return validateWorldSpec(next);}
 const session={get plannerRequest(){return clone(plannerRequest);},get plannerPreview(){return clone(plannerPreview);},get draft(){return getDraft();},get analysisTicket(){return revision;},get confirmation(){return clone(confirmation);},get printed(){return clone(printed);},get spec(){return world.spec;},get artifact(){return world.artifact;},get history(){return clone(history);},get canConfirm(){return blockers(draft).length===0;},get canPrint(){return confirmation!==null&&confirmation.revision===revision;},get status(){const bs=blockers(draft);return {stage:confirmation?'confirmed':!draft.analyzed?'writing':bs.length?'needs-review':'review-ready',blockers:clone(bs),canConfirm:bs.length===0,canPrint:session.canPrint,revision,analyzerLabel:clone(ANALYZER_LABEL)};},
 setStory(value){invalidate();text(value,LIMITS.story);draft=carryMetadata(emptyDraft(value),draft,value!==draft.sourceText);return getDraft();},
 loadPreparedExample(value){invalidate();text(value,LIMITS.story);draft=carryMetadata(emptyDraft(value,'prepared-synthetic-demo'),draft,value!==draft.sourceText);return getDraft();},
 setRevisionText(value){invalidate();text(value,LIMITS.revision);draft.revisionText=value;draft.revisionKind=value?'local-session-story':null;draft.revisionPending=!!value.trim();return getDraft();},
 analyze({expectedRevision=revision}={}){if(expectedRevision!==revision)throw Error('stale-analysis');if(draft.revisionPending)throw Error('revision-not-reviewed');if(draft.mode==='revision'&&draft.revisionText)return session.requestRevision(draft.revisionText);invalidate();draft=carryMetadata(analyzeStory(draft.sourceText,{dataKind:draft.dataKind}),draft);return getDraft();},
 updateBlueprint(patch){invalidate();if(!patch||typeof patch!=='object'||Array.isArray(patch)||Object.keys(patch).some(k=>!['title','summary','world','narrationMode'].includes(k)))throw Error('invalid-blueprint');const next=clone(draft);if(Object.hasOwn(patch,'title')){next.title=text(patch.title,LIMITS.title);next.metadata.titleOrigin='manual-session';next.metadata.titleRetained=false;}if(Object.hasOwn(patch,'summary')){next.summary=text(patch.summary,LIMITS.summary);next.metadata.narrationMode='edited';next.metadata.narrationOrigin='manual-session';next.metadata.narrationRetained=false;}if(Object.hasOwn(patch,'narrationMode')){if(!['none','original','edited'].includes(patch.narrationMode))throw Error('invalid-narration-mode');next.metadata.narrationMode=patch.narrationMode;next.metadata.narrationOrigin=patch.narrationMode==='original'?'sourceText':patch.narrationMode==='edited'?'manual-session':'none';next.metadata.narrationRetained=false;}if(Object.hasOwn(patch,'world')){if(!patch.world||typeof patch.world!=='object'||Array.isArray(patch.world)||Object.keys(patch.world).some(k=>!WORLD_KEYS.includes(k)))throw Error('invalid-blueprint');const s=world.spec;s.world={...next.world,...patch.world};validateWorldSpec(s);for(const key of Object.keys(patch.world)){next.world[key]=patch.world[key];next.fieldEvidence[key]={value:patch.world[key],origin:'session-input',quotes:[],reason:pair('Lựa chọn sửa thủ công trong phiên; không giả trích lời kể.','Manual session choice; no invented story quote.'),status:'manual-choice'};for(const i of next.issues)if(i.field===key&&i.kind!=='unsupported-world')i.resolved=true;}}draft=next;return getDraft();},
 acknowledge(id,value){invalidate();if(typeof value!=='boolean')throw Error('invalid-acknowledgement');const i=draft.issues.find(i=>i.id===id);if(!i||i.required)throw Error('required-issue');draft.acknowledgements[id]=value;return getDraft();},
 confirm(){if(blockers(draft).length)throw Error('unresolved-blueprint');const spec=specFromDraft();confirmation={revision,spec,blueprint:getDraft(),meaning:'In-session review only; no authenticated child or parent authorization.'};return clone(confirmation);},
 print(...args){if(args.length)throw Error('invalid-print-input');if(!session.canPrint)throw Error('unconfirmed-blueprint');const snapshot=clone(confirmation);const result=world.print(snapshot.spec);const unmet=draft.issues.filter(i=>!i.required&&!i.resolved).map(i=>({...clone(i),acknowledged:draft.acknowledgements[i.id]===true,fulfilled:false}));const story={...(draft.planner?{planner:clone(draft.planner),plannerSnapshot:clone(draft.planner.snapshot)}:{}),sourceText:draft.sourceText,source:draft.sourceText,sourceKind:draft.sourceKind,revisionText:draft.revisionText,revisionKind:draft.revisionKind,title:draft.title,summary:draft.summary,metadata:clone(draft.metadata),narration:artworkNarration(draft),fieldEvidence:clone(draft.fieldEvidence),blueprint:clone(snapshot.blueprint)};printed={spec:result.spec,story,unmetDetails:unmet,confirmedInSession:true,dataKind:draft.dataKind,printId:printed.printId+1};history=[...history,{printId:printed.printId,version:result.spec.version,changed:result.changed,rebuilt:result.rebuilt,difference:result.difference,story:clone(story),unmetDetails:clone(unmet)}].slice(-100);return {...result,printed:clone(printed)};},
 requestRevision(value){invalidate();text(value,LIMITS.revision,false);if(!printed.story)throw Error('no-printed-story');const previous=draft;draft=carryMetadata(analyzeStory(printed.story.sourceText,{priorSpec:printed.spec,priorStory:printed.story,priorPrintId:printed.printId,revisionText:value,dataKind:'local-session-story'}),previous,previous.sourceText!==printed.story.sourceText);draft.sourceKind=printed.story.sourceKind;return getDraft();},
 reset(){invalidate();const result=world.reset();draft=emptyDraft();printed={spec:result.spec,story:null,unmetDetails:[],confirmedInSession:false,dataKind:'prepared-synthetic-demo',printId:0};history=[];return result;},
 beginPlanner(context){invalidate();if(!context||typeof context!=='object'||Array.isArray(context)||Object.keys(context).length!==4||!['ageBand','goals','mentorNotes','answerNotes'].every(k=>Object.hasOwn(context,k)))throw Error('invalid-facilitation');if(draft.revisionPending)throw Error('revision-not-reviewed');const base=draft.mode==='revision'?printed:null;plannerRequest=validatePlannerSnapshot({schemaVersion:1,generation:revision,sourceText:draft.sourceText,revisionText:draft.mode==='revision'?draft.revisionText:'',basePrintId:base?.printId??null,baseSourceText:base?.story?.sourceText??'',baseRevisionText:base?.story?.revisionText??'',baseWorld:base?.spec?.world??null,...context});return clone(plannerRequest);},
 previewPlanner(plan,{request=plannerRequest,origin='imported-proposal'}={}){if(!plannerRequest||!request||request.generation!==revision||bindingFor(request)!==bindingFor(plannerRequest))throw Error('stale-planner');if(!['prepared-planner','imported-proposal','ai-proposal'].includes(origin))throw Error('invalid-planner-origin');const valid=validatePlannerPlan(plan,request);plannerPreview={plan:valid,request:clone(request),origin,adopted:false};return clone(plannerPreview);},
 invalidatePlanner(){invalidate();return getDraft();},
 adoptPlanner({locale='vi'}={}){if(!['vi','en'].includes(locale))throw Error('invalid-locale');if(!plannerPreview||!plannerRequest||plannerPreview.request.generation!==revision)throw Error('stale-planner');const preview=clone(plannerPreview),valid=validatePlannerPlan(preview.plan,preview.request);const next=draft.analyzed?clone(draft):carryMetadata(analyzeStory(draft.sourceText,{dataKind:draft.dataKind}),draft);const origin=preview.origin==='prepared-planner'?'offline-suggestion':preview.origin;// Planner titles/reflections remain method/proposal content; authored metadata is retained.
 const enrich=quotes=>quotes.map(q=>({...clone(q),sourceTextSnapshot:/^answerNote[012]$/.test(q.source)?preview.request.answerNotes[Number(q.source.at(-1))]:preview.request[q.source],requestGeneration:preview.request.generation}));for(const k of WORLD_KEYS){const p=valid.proposals[k],priorChoice=next.fieldEvidence[k];if(priorChoice.status!=='default-proposal'&&next.world[k]!==p.value){next.issues.push(issue('planner-conflict-'+preview.request.generation+'-'+k,'conflict',k,true,pair('Đề xuất khác lựa chọn đã có trong lời kể/bản đã duyệt. Hãy chọn rõ trường này trước khi xác nhận.','Proposal differs from an explicit story or previously reviewed choice. Select this field explicitly before confirmation.'),clone(priorChoice.quotes)));}next.world[k]=p.value;next.fieldEvidence[k]={value:p.value,origin,quotes:enrich(p.evidence),reason:clone(p.rationale),status:'planner-proposal'};}for(const u of valid.unrendered){const id='planner-'+preview.request.generation+'-'+u.id,evidence=enrich(u.evidence);const evidenceKey=list=>JSON.stringify(list.map(q=>({source:q.source,start:q.start,end:q.end,text:q.text,sourceTextSnapshot:q.sourceTextSnapshot??(q.source==='sourceText'?next.sourceText:q.source==='revisionText'?next.revisionText:undefined),...(q.source==='prior-print'?{printId:q.printId,sourceField:q.sourceField}:{})})));const existing=next.issues.find(i=>i.required===u.required&&i.field===u.field&&i.message.vi===u.reason.vi&&i.message.en===u.reason.en&&evidenceKey(i.evidence)===evidenceKey(evidence));if(existing){existing.plannerReferences=[...(existing.plannerReferences||[]),{id:u.id,origin:preview.origin,requestGeneration:preview.request.generation}].slice(-16);}else next.issues.push(issue(id,u.required?'unknown':'unmet',u.field,u.required,clone(u.reason),evidence));}if(next.issues.length>64)throw Error('too-many-issues');next.planner={origin,plan:valid,snapshot:clone(preview.request),status:'adopted-not-confirmed',meaning:'Planner proposal, not authenticated child words or live-result verification.'};next.analyzed=true;next.revisionPending=false;const spec=world.spec;spec.world=clone(next.world);validateWorldSpec(spec);invalidate();draft=next;return getDraft();},
 dispose(){invalidate();world.dispose();},
 exportProject(){return {plannerRequest:clone(plannerRequest),plannerPreview:clone(plannerPreview),schemaVersion:1,kind:'local-in-memory-story-project',analyzerLabel:clone(ANALYZER_LABEL),draft:getDraft(),confirmation:clone(confirmation),printed:clone(printed),history:clone(history),limits:clone(LIMITS),scope:'Session input and explicit in-session confirmation; no live model, authenticated child identity or educational validation.'};}
 };return session;
}
export function exportProject(session){if(!session||typeof session.exportProject!=='function')throw Error('invalid-session');return session.exportProject();}
