import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import {spawn} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {mkdtemp,writeFile,mkdir,symlink,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {createLabServer,configuredPort,startLabServer} from '../serve.mjs';import {createProvider} from '../provider.mjs';import {snapshotForFixture} from '../fixtures/prepared.js';
async function start(t,options={}){const s=createLabServer(options);await new Promise((ok,fail)=>{s.once('error',fail);s.listen(0,'127.0.0.1',ok);});t.after(()=>new Promise(ok=>s.close(ok)));const url='http://127.0.0.1:'+s.address().port;return {s,url};}
const payload=()=>({fixtureId:'vi-whale',snapshot:snapshotForFixture('vi-whale')});
const post=(url,data=payload(),extras={})=>fetch(url+'/api/planner',{method:'POST',headers:{Origin:url,'Content-Type':'application/json',...extras.headers},body:typeof data==='string'?data:JSON.stringify(data),...extras});
test('real loopback config is safe/OFF and valid live request is disabled',async t=>{let calls=0;const {url}=await start(t,{provider:createProvider({config:{enabled:false},transport:()=>{calls++;}})});const config=await(await fetch(url+'/api/config')).json();assert.equal(config.enabled,false);assert.equal(config.liveStatus,'OFF');assert.equal(config.model,null);assert.equal(JSON.stringify(config).includes('apiKey'),false);const r=await post(url);assert.equal(r.status,503);assert.equal((await r.json()).error,'provider-disabled');assert.equal(calls,0);});
test('API rejects wrong method/origin/content type and extra request fields',async t=>{const {url}=await start(t);assert.equal((await fetch(url+'/api/planner')).status,405);assert.equal((await fetch(url+'/api/planner',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,403);assert.equal((await fetch(url+'/api/planner',{method:'POST',headers:{Origin:url,'Content-Type':'text/plain'},body:'{}'})).status,415);assert.equal((await post(url,{...payload(),extra:'x'})).status,400);assert.equal((await post(url,'not JSON')).status,400);});
test('Host guard rejects alternate host before route or provider',async t=>{const {s}=await start(t);const result=await new Promise((ok,fail)=>{const req=http.get({host:'127.0.0.1',port:s.address().port,path:'/api/config',headers:{Host:'evil.invalid'}},res=>{res.resume();res.on('end',()=>ok(res.statusCode));});req.on('error',fail);});assert.equal(result,403);});
test('static allowlist refuses private/research/server/provider/metadata paths',async t=>{const {url}=await start(t);assert.equal((await fetch(url+'/')).status,200);assert.equal((await fetch(url+'/planner.js')).status,200);assert.equal((await fetch(url+'/journey.js')).status,200);for(const p of ['/provider.mjs','/server.mjs','/.env','/.git/config','/research/fulltexts/SRC08.pdf','/delivery/DREAM-P03/TIP.md','/kit/render.py','/package.json','/tests/planner.test.mjs','/%2eenv'])assert.equal((await fetch(url+p)).status,404,p);});
test('body byte limit and counterfeit fixture context fail before provider',async t=>{let calls=0;const {url}=await start(t,{provider:{status:()=>({enabled:false}),plan:()=>{calls++;return {};}}});assert.equal((await post(url,' '.repeat(65537))).status,413);const bad=payload();bad.snapshot.answerNotes=['private'];assert.equal((await post(url,bad)).status,422);assert.equal(calls,0);});
test('exact public kit allowlist includes authored downloads and rejects tooling/symlink escape',async t=>{const dir=await mkdtemp(path.join(os.tmpdir(),'dream-lab-test-')),lab=path.join(dir,'lab'),kit=path.join(dir,'kit');await mkdir(lab);await mkdir(kit);await writeFile(path.join(kit,'index.html'),'<h1>synthetic kit</h1>');await writeFile(path.join(kit,'CONTENT.json'),'{}');for(const name of['rehearsal.vi.html','rehearsal.en.html','observation-template.json','synthetic-scenarios.json','observation.csv'])await writeFile(path.join(kit,name),'synthetic '+name);await writeFile(path.join(dir,'secret'),'synthetic private marker');await symlink(path.join(dir,'secret'),path.join(lab,'main.js'));t.after(()=>rm(dir,{recursive:true,force:true}));const {url}=await start(t,{labRoot:lab,kitRoot:kit});assert.equal((await fetch(url+'/kit/')).status,200);assert.equal((await fetch(url+'/kit/CONTENT.json')).status,200);for(const name of['rehearsal.vi.html','rehearsal.en.html','observation-template.json','synthetic-scenarios.json','observation.csv']){const response=await fetch(url+'/kit/'+name);assert.equal(response.status,200);assert.equal(await response.text(),'synthetic '+name);assert.match(response.headers.get('content-type'),name.endsWith('.csv')?/text\/csv/:name.endsWith('.json')?/application\/json/:/text\/html/);}assert.equal((await fetch(url+'/kit/BUILD.json')).status,404);assert.equal((await fetch(url+'/main.js')).status,404);});

test('startup port is bounded, defaults8882 and invalid configuration fails with actionable message',()=>{assert.equal(configuredPort({}),8882);assert.equal(configuredPort({DREAM_LAB_PORT:'8885'}),8885);for(const value of ['0','80','65536','abc','8882x',''])assert.throws(()=>configuredPort({DREAM_LAB_PORT:value}),/invalid-port/);const messages=[];assert.equal(startLabServer({env:{DREAM_LAB_PORT:'bad'},error:message=>messages.push(message)}),null);assert.match(messages[0],/1024 to 65535/);});

test('actual occupied port startup exits2 with recovery guidance and leaves existing server intact',async t=>{const {s,url}=await start(t);const child=spawn(process.execPath,[fileURLToPath(new URL('../server.mjs',import.meta.url))],{env:{...process.env,DREAM_AI_ENABLED:'false',DREAM_LAB_PORT:String(s.address().port)}});let stderr='';child.stderr.on('data',chunk=>stderr+=chunk);const code=await new Promise((resolve,reject)=>{child.on('error',reject);child.on('close',resolve);});assert.equal(code,2);assert.match(stderr,/already in use/);assert.match(stderr,/No process was stopped/);assert.ok(!stderr.includes('Unhandled'));assert.equal((await fetch(url+'/api/config')).status,200);});
