#!/usr/bin/env node
// Dependency-free static release boundary. Same exact runtime output for Git, CLI and CI.
import fs from 'node:fs/promises';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath}from'node:url';
const ROOT=path.resolve(fileURLToPath(new URL('..',import.meta.url)));
const ROOMS=['group','activity','session','reports','workbench','library','guide','review'];
export const RUNTIME=Object.freeze(['index.html','styles.css','main.js','model.js','provider.js','locale.js','resources-client.js','legacy-p01.js','handoff.js','motion.js','room-ui.js','references-client.js','favicon.svg','assets/brandmark.svg','assets/explorer-world.svg','assets/star-path.svg','assets/rose-mark.svg',...ROOMS.map(n=>'assets/rooms/'+n+'.svg'),'assets/fonts/Lora.ttf','assets/fonts/Lora-OFL.txt','assets/fonts/BeVietnamPro-Regular.ttf','assets/fonts/BeVietnamPro-SemiBold.ttf','assets/fonts/BeVietnamPro-OFL.txt','references/catalog.json','references/report.html']);
export const DREAM=Object.freeze(['index.html','main.js','style.css','public-mode.js','world.js','story.js','planner.js','notebook.js','lab.js','journey.js','scene.js','fixtures/prepared.js','vendor/three.module.js','vendor/three.core.js','vendor/OrbitControls.js','vendor/THREE-LICENSE.txt']);
const KIT=['index.html','rehearsal.vi.html','rehearsal.en.html','observation.csv','observation-template.json','synthetic-scenarios.json'];
const fp=raw=>({bytes:raw.length,sha256:crypto.createHash('sha256').update(raw).digest('hex')});
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b);const require=(v,m)=>{if(!v)throw Error(m)};
async function source(root,relative){require(typeof relative==='string'&&relative===relative.replaceAll('\\','/')&&!path.isAbsolute(relative)&&relative.split('/').every(p=>p&&p!=='.'&&p!=='..'),'unsafe static source path: '+relative);let p=root;for(const part of relative.split('/')){p=path.join(p,part);const stat=await fs.lstat(p);require(!stat.isSymbolicLink(),'static source symlink: '+relative);}return fs.readFile(p);}
async function exists(p){try{await fs.lstat(p);return true}catch(e){if(e.code==='ENOENT')return false;throw e}}
async function list(root,prefix=''){let out=[];for(const entry of await fs.readdir(path.join(root,prefix),{withFileTypes:true})){const n=prefix+entry.name;require(!entry.isSymbolicLink(),'output symlink forbidden: '+n);if(entry.isDirectory())out.push(...await list(root,n+'/'));else{require(entry.isFile(),'nonfile static output: '+n);out.push(n)}}return out.sort()}
export async function collectSite(root=ROOT){root=path.resolve(root);const outputs=new Map(),inputs={};
 async function add(relative,expected){const name='app/'+relative,raw=await source(root,name),row=fp(raw);if(expected)require(row.sha256===expected,'compiled source drift: '+name);require(!outputs.has(relative),'duplicate output: '+relative);outputs.set(relative,raw);inputs[name]=row;}
 for(const n of RUNTIME)await add(n);for(const n of DREAM)await add('dream/'+n);
 const refsRaw=await source(root,'app/references/build.json'),refs=JSON.parse(refsRaw);inputs['app/references/build.json']=fp(refsRaw);require(refs.schemaVersion===1&&same(Object.keys(refs.files).sort(),['catalog.json','report.html']),'reference output inventory mismatch');for(const n of['catalog.json','report.html']){const raw=await source(root,'app/references/'+n),row=fp(raw);require(row.bytes===refs.files[n].bytes&&row.sha256===refs.files[n].sha256,'reference generated source drift: '+n);require(inputs['app/references/'+n].sha256===row.sha256,'reference copied source drift: '+n)}

 const resourcesRaw=await source(root,'app/resources/manifest.json'),resources=JSON.parse(resourcesRaw);inputs['app/resources/manifest.json']=fp(resourcesRaw);require(resources.outputs&&Object.keys(resources.outputs).length>0,'resource output inventory missing');for(const[n,sha]of Object.entries(resources.outputs).sort())await add('resources/'+n,sha);
 const kitRaw=await source(root,'app/dream/kit/BUILD.json'),kit=JSON.parse(kitRaw);inputs['app/dream/kit/BUILD.json']=fp(kitRaw);require(kit.schemaVersion===2&&same(Object.keys(kit.files).sort(),KIT.slice().sort()),'kit output inventory mismatch');for(const n of KIT){const raw=await source(root,'app/dream/kit/'+n);require(same(fp(raw),kit.files[n]),'kit generated source drift: '+n);await add('dream/kit/'+n)}
 // Authored canonical content is a public source input, not a production endpoint.
 const kitContent=await source(root,'app/dream/kit/CONTENT.json');inputs['app/dream/kit/CONTENT.json']=fp(kitContent);require(fp(kitContent).sha256===kit.sourceSha256,'kit canonical content drift');const template=JSON.parse(outputs.get('dream/kit/observation-template.json'));require(template.observerConfirmation===null&&template.printId===null&&template.observationStatus==='not-observed','kit must remain blank/unobserved');
 const archive=await source(root,'app/downloads/project-review-WEB02.zip'),outerRaw=await source(root,'app/downloads/project-review-WEB02.json'),outer=JSON.parse(outerRaw);require(outer.bytes===archive.length&&outer.sha256===fp(archive).sha256,'review archive/receipt drift');await add('downloads/project-review-WEB02.zip');await add('downloads/project-review-WEB02.json');
 const main=outputs.get('dream/main.js').toString();require(!/\b(?:fetch|XMLHttpRequest|WebSocket|EventSource)\s*\(/.test(main)&&!main.includes('/api/'),'public Dream network entry forbidden');
 const files=Object.fromEntries([...outputs].sort(([a],[b])=>a<b?-1:a>b?1:0).map(([n,b])=>[n,fp(b)]));const orderedInputs=Object.fromEntries(Object.entries(inputs).sort(([a],[b])=>a<b?-1:a>b?1:0));
 const fingerprint=fp(Buffer.from(JSON.stringify({inputs:orderedInputs,files}))).sha256;return {outputs,receipt:{schemaVersion:1,kind:'runtime-only-static-site',edition:'DEPLOY-CLEANUP-20261007',sourceRoot:'app',outputDirectory:'dist',inputs:orderedInputs,files,fingerprint,liveAI:'PERMANENTLY_OFF_STATIC',limits:'Exact source/output integrity, not educational/accessibility approval or a signature. Source-only backend/tests/compiler metadata are excluded from served routes.'}};
}
async function releaseRoots(root){for(const n of['dist','.vercel']){const p=path.join(root,n);if(await exists(p)){const st=await fs.lstat(p);require(st.isDirectory()&&!st.isSymbolicLink(),'release root symlink/non-directory forbidden: '+n)}}const receipt=path.join(root,'.vercel/static-site-receipt.json');if(await exists(receipt)){const st=await fs.lstat(receipt);require(st.isFile()&&!st.isSymbolicLink(),'release receipt symlink/nonfile forbidden')}}
export async function buildSite(root=ROOT){root=path.resolve(root);await releaseRoots(root);const {outputs,receipt}=await collectSite(root),dest=path.join(root,'dist'),meta=path.join(root,'.vercel/static-site-receipt.json');
 if(await exists(dest)){const stat=await fs.lstat(dest);require(stat.isDirectory()&&!stat.isSymbolicLink(),'dist must be a managed directory');require(await exists(meta),'refuse to replace unmanaged dist');const old=JSON.parse(await fs.readFile(meta));require(old.kind==='runtime-only-static-site'&&same(await list(dest),Object.keys(old.files).sort()),'refuse to replace unlisted dist content');}
 if(await exists(path.join(root,'.vercel')))require(!(await fs.lstat(path.join(root,'.vercel'))).isSymbolicLink(),'build metadata symlink forbidden');await fs.mkdir(path.join(root,'.vercel'),{recursive:true});const stage=await fs.mkdtemp(path.join(root,'.vercel/static-stage-'));let backup=null;
 try{for(const[n,raw]of outputs){const target=path.join(stage,n);await fs.mkdir(path.dirname(target),{recursive:true});await fs.writeFile(target,raw)}if(await exists(dest)){backup=await fs.mkdtemp(path.join(root,'.vercel/static-old-'));await fs.rmdir(backup);await fs.rename(dest,backup)}try{await fs.rename(stage,dest)}catch(e){if(backup)await fs.rename(backup,dest);throw e}await fs.writeFile(meta,JSON.stringify(receipt,null,2)+'\n');if(backup)await fs.rm(backup,{recursive:true});return receipt;}catch(e){await fs.rm(stage,{recursive:true,force:true});throw e}
}
export async function verifySite(root=ROOT){root=path.resolve(root);await releaseRoots(root);const {receipt}=await collectSite(root),dest=path.join(root,'dist'),actual=JSON.parse(await fs.readFile(path.join(root,'.vercel/static-site-receipt.json')));require(same(receipt,actual),'static receipt source drift');require(same(await list(dest),Object.keys(receipt.files).sort()),'static output inventory drift');for(const[n,row]of Object.entries(receipt.files))require(same(fp(await source(dest,n)),row),'static output bytes drift: '+n);return receipt;}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){try{require(process.argv.slice(2).every(x=>x==='--check'),'unknown static build argument');const r=process.argv.includes('--check')?await verifySite():await buildSite();console.log(JSON.stringify({status:'PASS',files:Object.keys(r.files).length,bytes:Object.values(r.files).reduce((s,r)=>s+r.bytes,0),fingerprint:r.fingerprint,outputDirectory:r.outputDirectory,receipt:'.vercel/static-site-receipt.json'},null,2))}catch(e){console.error(JSON.stringify({status:'FAIL',error:e.message}));process.exitCode=2;}}
