import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {MOTION_KEY,readMotionPreference,writeMotionPreference,effectiveMotion,createMotionControl} from '../motion.js';
const memory=()=>{const values=new Map();return {values,getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value)};};
function fixture(storage,lang='vi',reduced=false){const events={},attributes={};const button={dataset:{},setAttribute:(key,value)=>attributes[key]=value,addEventListener:(key,fn)=>events[key]=fn};const media={matches:reduced,addEventListener:(key,fn)=>events['media-'+key]=fn};let locale=lang;globalThis.document={body:{dataset:{}}};const control=createMotionControl({storage,button,media,locale:()=>locale});return {button,media,attributes,control,events,setLocale:value=>locale=value};}
test('visual preference is separate from learning/review records and persists across visits',()=>{const storage=memory();storage.setItem('thuy-anh-ai-learning:p01:v1','existing learning');storage.setItem('thuy-anh-ai-learning:project-review:v1','original feedback');assert.equal(readMotionPreference(storage).enabled,true);assert.equal(writeMotionPreference(storage,false),null);assert.equal(readMotionPreference(storage).enabled,false);assert.equal(storage.values.size,3);assert.equal(storage.getItem('thuy-anh-ai-learning:p01:v1'),'existing learning');assert.equal(storage.getItem('thuy-anh-ai-learning:project-review:v1'),'original feedback');assert.equal(storage.getItem(MOTION_KEY),'off');});
test('system reduced motion takes precedence without replacing the stored preference',()=>{const storage=memory(),f=fixture(storage,'en',true);assert.equal(document.body.dataset.motion,'reduced');assert.equal(f.button.disabled,true);assert.equal(f.button.textContent,'System reduced motion');f.events.click();assert.equal(storage.getItem(MOTION_KEY),null);f.media.matches=false;f.events['media-change']();assert.equal(document.body.dataset.motion,'on');assert.equal(f.button.textContent,'Pause motion');assert.equal(f.button.disabled,false);assert.equal(effectiveMotion(false,true),'reduced');});
test('pause survives reload and both control languages resynchronize without changing user data',()=>{const storage=memory(),f=fixture(storage);f.events.click();assert.equal(document.body.dataset.motion,'off');assert.equal(f.button.textContent,'Bật chuyển động');assert.equal(f.attributes['aria-pressed'],'false');f.setLocale('en');f.control.sync();assert.equal(f.button.textContent,'Enable motion');const next=fixture(storage,'en');assert.equal(document.body.dataset.motion,'off');next.events.click();assert.equal(next.button.textContent,'Pause motion');assert.equal(storage.getItem(MOTION_KEY),'on');});
test('invalid or unavailable preference fails to a quiet static view and blocked writes retain the active choice',()=>{const storage=memory();storage.setItem(MOTION_KEY,'unrecognised');assert.equal(readMotionPreference(storage).enabled,false);assert.equal(readMotionPreference(storage).error,'invalid-preference');const blocked={getItem(){throw Error('blocked');},setItem(){throw Error('quota');}};const f=fixture(blocked,'en');assert.equal(document.body.dataset.motion,'off');assert.ok(f.button.title.includes('current visit'));f.events.click();assert.equal(document.body.dataset.motion,'on');assert.ok(f.button.title.includes('current visit'));assert.equal(writeMotionPreference(blocked,false),'unavailable-storage');});
test('illustrations are local, bounded effects have no continuous loop, and reduced motion disables transitions',()=>{const css=fs.readFileSync(new URL('../styles.css',import.meta.url),'utf8'),runtime=fs.readFileSync(new URL('../motion.js',import.meta.url),'utf8');assert.match(css,/explorer-arrival 7s ease-out 1 both/);assert.match(css,/star-trail 10s ease-out 1 both/);assert.ok(!runtime.includes('requestAnimationFrame'));assert.ok(!css.includes('infinite'));assert.match(css,/body\[data-motion=off\][\s\S]*animation:none!important;transition:none!important/);assert.match(css,/@media\(prefers-reduced-motion:reduce\)[\s\S]*transition:none!important/);for(const name of ['explorer-world.svg','rose-mark.svg','star-path.svg']){const svg=fs.readFileSync(new URL('../assets/'+name,import.meta.url),'utf8');assert.ok(!/<script|<animate|https?:\/\//i.test(svg.replace('http://www.w3.org/2000/svg','')));assert.match(svg,/<svg/);}});
