import test from 'node:test';
import assert from 'node:assert/strict';
import {freshState,startSession,setAnswer,pauseSession,backupJSON,restoreJSON,addObservation,recordReadiness,activityPresentation,reviseActivity,seedLessons,validateActivity,seedTranslationCandidates,upgradeSeedTranslations,workbenchText,STEPS,receiveAI,advance} from '../model.js';
import {readLocale,writeLocale,translate,localizedCatalogItem} from '../locale.js';
import {readFileSync} from 'node:fs';
const lessons=JSON.parse(readFileSync(new URL('../../materials/curriculum/lessons.json',import.meta.url)));
test('v2 migration preserves all pinned content, answers, rating and events exactly',()=>{const s=freshState();const session=startSession(s,'MAU-001');setAnswer(session,'initial','Bài ban đầu / original text');pauseSession(session);const old=structuredClone(s);old.schemaVersion=2;delete old.observations;delete old.readiness;const before=structuredClone(old);const restored=restoreJSON(JSON.stringify(old));assert.equal(restored.schemaVersion,3);assert.deepEqual(restored.sessions,before.sessions);assert.deepEqual(restored.activities,before.activities);assert.deepEqual(restored.learners,before.learners);assert.deepEqual(restored.observations,[]);assert.deepEqual(restored.readiness,[]);});
test('locale preference is independent of state and safely falls back under storage denial',()=>{const data=new Map();const storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)};const s=freshState(),before=structuredClone(s);assert.equal(readLocale(storage),'vi');writeLocale(storage,'en');assert.equal(readLocale(storage),'en');assert.deepEqual(s,before);assert.equal(readLocale({getItem(){throw Error('denied');}}),'vi');assert.equal(typeof writeLocale({setItem(){throw Error('denied');}},'en'),'string');assert.throws(()=>writeLocale(storage,'fr'));});
test('authored English presentation does not mutate or revise pinned content',()=>{const s=freshState();seedLessons(s,lessons);s.selectedActivityId=lessons.lessons[1].id;const session=startSession(s,'MAU-001'),before=structuredClone(session);setAnswer(session,'initial','Học viên tự viết · learner text');const en=activityPresentation(session.activity,'en');assert.equal(en.title,lessons.lessons[1].translations.en.title);assert.equal(en.contentLanguage,'en');assert.equal(en.translationFallback,false);en.instructions.initial='temporary presentation';assert.deepEqual(session.activity,before.activity);assert.equal(session.answers.initial,'Học viên tự viết · learner text');assert.equal(s.activities.length,4);reviseActivity(s,{title:'Edited local activity',goal:'Original local text'});assert.equal(activityPresentation(s.activities.at(-1),'en').translationFallback,true);});
test('unknown legacy translation is explicitly marked and original language retained',()=>{const activity=freshState().activities[0],en=activityPresentation(activity,'en');assert.equal(en.title,activity.title);assert.equal(en.translationFallback,true);assert.equal(en.contentLanguage,'vi');});
test('observation distinguishes report from interpretation and round trips with backup',()=>{const s=freshState(),session=startSession(s,'MAU-001');const before=structuredClone(session);addObservation(s,{sessionId:session.id,observer:'DEMO-OBSERVER',description:'Synthetic participant report',issue:'Follow-up required',kind:'reported',support:'hint',minutes:2.5});assert.deepEqual(session,before);assert.equal(s.observations[0].step,0);const restored=restoreJSON(backupJSON(s));assert.deepEqual(restored.observations,s.observations);assert.equal(restored.observations[0].scope,'synthetic-adult-rehearsal');});
test('invalid observations are rejected atomically; forged scope and missing session fail restore',()=>{const s=freshState(),session=startSession(s,'MAU-001');const valid={sessionId:session.id,observer:'DEMO',description:'Observed event',issue:'',kind:'observed',support:'none',minutes:1};for(const bad of[{minutes:-1},{minutes:Infinity},{kind:'claim'},{observer:''},{description:''},{support:'secret'},{sessionId:'missing'}]){assert.throws(()=>addObservation(s,{...valid,...bad}));assert.equal(s.observations.length,0);}addObservation(s,valid);for(const mutate of[x=>x.observations[0].scope='pilot-approved',x=>x.observations[0].sessionId='missing',x=>x.observations[0].activityVersion=999,x=>x.observations.push(x.observations[0])]){const forged=structuredClone(s);mutate(forged);assert.throws(()=>restoreJSON(JSON.stringify(forged)));}});
test('readiness never defaults ready and requires rationale; old versions are not approvals',()=>{const s=freshState();assert.deepEqual(s.readiness,[]);assert.throws(()=>recordReadiness(s,{key:'lesson-review',status:'ready-for-adult-rehearsal',owner:'',note:'',version:'LES-02-v1'}));assert.equal(s.readiness.length,0);recordReadiness(s,{key:'lesson-review',status:'in-progress',owner:'DEMO',note:'External review pending',version:'LES-02-v1'});recordReadiness(s,{key:'lesson-review',status:'needs-revision',owner:'DEMO',note:'Draft changes required',version:'LES-02-v1'});assert.equal(s.readiness.length,1);assert.equal(s.readiness[0].scope,'local-only-not-pilot-approval');assert.deepEqual(restoreJSON(backupJSON(s)).readiness,s.readiness);});
test('catalog selection retains IDs/source attribution and marks missing English explicitly',()=>{const original={id:'DOC',title:'Việt',description:'Nháp',href:'resources/vi.md',sourceIds:['SRC-01'],category:'research',translations:{en:{title:'English',description:'Draft',href:'resources/en/vi.md'}}};const before=structuredClone(original);const en=localizedCatalogItem(original,'en');assert.equal(en.href,'resources/en/vi.md');assert.deepEqual(en.sourceIds,original.sourceIds);assert.equal(en.id,'DOC');assert.deepEqual(original,before);assert.equal(localizedCatalogItem({...original,translations:null},'en').translationFallback,true);});
test('interface translation uses authored copy and reports control labels',()=>{assert.equal(translate('Xuất báo cáo','en'),'Export report');assert.equal(translate('Tạm dừng phiên','en'),'Pause session');assert.equal(translate('Tạm dừng','en'),'Paused');assert.equal(translate('Tiếp tục phiên','en'),'Resume session');assert.equal(translate('Không tìm thấy phiên quan sát.','en'),'Observation session not found.');assert.equal(translate('Hello custom text','en'),'Hello custom text');});
test('English revision in source cannot change an already pinned English session',()=>{const s=freshState();seedLessons(s,lessons);s.selectedActivityId=lessons.lessons[1].id;const session=startSession(s,'MAU-001');const before=activityPresentation(session.activity,'en');const changed=structuredClone(lessons);changed.lessons[1].translations.en.title='Updated English source';seedLessons(s,changed);assert.deepEqual(activityPresentation(session.activity,'en'),before);assert.equal(s.activities.filter(a=>a.id===session.activity.id).length,1);});
test('malformed authored translation rejects seeding without partial changes',()=>{const s=freshState(),before=structuredClone(s);for(const mutate of[p=>p.lessons[0].translations.en.instructions.initial='',p=>p.lessons[0].translations.en.rubric[0].key='forged',p=>p.lessons[0].translations.en.sourceCards[0].text='x'.repeat(4001),p=>p.lessons[0].translations.en.id='other']){const payload=structuredClone(lessons);mutate(payload);assert.throws(()=>seedLessons(s,payload));assert.deepEqual(s,before);}});

test('explicit English upgrade appends once and preserves existing sessions plus custom source edits',()=>{const s=freshState();const old=structuredClone(lessons);old.lessons.forEach(l=>delete l.translations);seedLessons(s,old);s.selectedActivityId=old.lessons[0].id;const session=startSession(s,'MAU-001');setAnswer(session,'initial','original answer');session.evaluation.note='old observation';const before=structuredClone(session),originalActivities=structuredClone(s.activities),selected=s.selectedActivityId;assert.equal(seedTranslationCandidates(s,lessons).length,3);assert.equal(upgradeSeedTranslations(s,lessons),3);assert.deepEqual(s.activities.slice(0,4),originalActivities);assert.deepEqual(session,before);assert.equal(s.selectedActivityId,selected);assert.equal(upgradeSeedTranslations(s,lessons),0);assert.equal(s.activities.length,7);const next=startSession(s,'MAU-002');assert.equal(next.activity.version,2);assert.equal(activityPresentation(next.activity,'en').translationFallback,false);assert.doesNotThrow(()=>restoreJSON(backupJSON(s)));const custom=freshState();seedLessons(custom,old);custom.selectedActivityId=old.lessons[1].id;reviseActivity(custom,{goal:'Custom authored objective'});const customBefore=structuredClone(custom.activities.at(-1));assert.equal(upgradeSeedTranslations(custom,lessons),2);assert.deepEqual(custom.activities.find(a=>a.id===customBefore.id&&a.version===2),customBefore);assert.equal(activityPresentation(customBefore,'en').translationFallback,true);});

test('localized rehearsal export labels enums without translating entered evidence or changing raw data',()=>{const state=freshState(),session=startSession(state,'MAU-001');addObservation(state,{sessionId:session.id,observer:'DEMO',description:'Bài kể lại nguyên văn',issue:'Ghi chú tiếng Việt',kind:'reported',support:'none',minutes:3});recordReadiness(state,{key:'lesson-review',status:'in-progress',owner:'DEMO',note:'Giữ ghi chú gốc',version:'LES-02-v1'});const before=structuredClone(state),en=JSON.parse(workbenchText(state,'en'));assert.equal(en.presentation.observations[0].support,'No support');assert.equal(en.presentation.observations[0].evidenceType,'Participant report');assert.equal(en.presentation.readiness[0].status,'In progress');assert.deepEqual(en.observations,state.observations);assert.deepEqual(en.readiness,state.readiness);assert.deepEqual(state,before);assert.equal(JSON.parse(workbenchText(state,'vi')).presentation.observations[0].support,'Không hỗ trợ');});

test('reload migrated v2 completed session with cached pre-context P03 observation safely derives only missing context',()=>{const original=freshState(),session=startSession(original,'MAU-001');for(const step of STEPS.slice(0,-1)){if(step.key==='ai')receiveAI(session,session.activity.sampleResponse);else setAnswer(session,step.key,`Synthetic answer ${step.key}`);advance(session);}session.evaluation={reviewer:'DEMO-REVIEWER',scores:{verification:1,explanation:2,independent:1},note:'Original synthetic note'};advance(session);original.schemaVersion=2;delete original.observations;delete original.readiness;const migrated=restoreJSON(JSON.stringify(original)),before=structuredClone(migrated.sessions);addObservation(migrated,{sessionId:session.id,kind:'interpretation',support:'none',minutes:3,observer:'QA-P03-DIRTY',description:'Synthetic QA only',issue:''});recordReadiness(migrated,{key:'backup-recovery',status:'in-progress',owner:'QA-CONTRACTOR',version:'P03',note:'Synthetic QA'});const cached=structuredClone(migrated);for(const field of['activityId','activityVersion','learnerId'])delete cached.observations[0][field];const rawBefore=structuredClone(cached),restored=restoreJSON(JSON.stringify(cached));assert.deepEqual(cached,rawBefore);assert.deepEqual(restored.sessions,before);assert.equal(restored.observations[0].step,7);assert.equal(restored.observations[0].activityId,session.activity.id);assert.equal(restored.observations[0].activityVersion,session.activity.version);assert.equal(restored.observations[0].learnerId,session.learnerId);assert.deepEqual(restored.readiness,migrated.readiness);const reloaded=restoreJSON(backupJSON(restored));assert.deepEqual({...reloaded,savedAt:restored.savedAt},restored);for(const modify of[x=>x.observations[0].activityId='FORGED',x=>x.observations[0].learnerId='FORGED',x=>x.observations[0].activityVersion=999,x=>x.observations[0].sessionId='missing']){const partial=structuredClone(cached);modify(partial);assert.throws(()=>restoreJSON(JSON.stringify(partial)));}});
