import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import * as legacy from '../legacy-p01.js';
import {freshState,restoreJSON,backupJSON,loadState,STORAGE_KEY,selectedActivity,latestActivities,selectActivity,seedLessons,createActivity,reviseActivity,reviewActivity,startSession,setAnswer,advance,receiveAI,activitySteps,validateActivity,reportText} from '../model.js';
import {requestSample} from '../provider.js';
import {validateCatalog,safeMarkdown,resolveDocumentLink} from '../resources-client.js';
const lessons=JSON.parse(await readFile(new URL('../../materials/curriculum/lessons.json',import.meta.url),'utf8'));
const seeded=()=>{const state=freshState();seedLessons(state,lessons);return state;};
test('valid P01 backup migrates with same answers, reviewer, events, dates and original lesson',()=>{const old=legacy.freshState(),s=legacy.startSession(old,'MAU-001');legacy.setAnswer(s,'initial','Bài cũ');legacy.advance(s);legacy.receiveAI(s,{text:'Phản hồi P01 từng được lưu khác fixture mặc định.',provenance:'Phản hồi AI mẫu · cố ý có lỗi'});legacy.advance(s);legacy.setAnswer(s,'concern','Cần đối chiếu');legacy.pauseSession(s);s.evaluation.reviewer='Mã đánh giá cũ';const migrated=restoreJSON(legacy.backupJSON(old));assert.equal(migrated.schemaVersion,3);assert.equal(migrated.selectedActivityId,'LEGACY-MATH01');assert.deepEqual(migrated.sessions[0].answers,s.answers);assert.deepEqual(migrated.sessions[0].events,s.events);assert.deepEqual(migrated.sessions[0].aiResponse,s.aiResponse);assert.deepEqual(migrated.sessions[0].evaluation,s.evaluation);assert.equal(migrated.sessions[0].status,'paused');assert.equal(migrated.sessions[0].step,2);assert.equal(migrated.sessions[0].startedAt,s.startedAt);assert.deepEqual(migrated.sessions[0].activity.sourceCards,s.activity.sourceCards);assert.equal(activitySteps(migrated.sessions[0].activity)[6].instruction,legacy.STEPS[6].instruction);});
test('failed legacy migration does not overwrite raw localStorage',()=>{const old=legacy.freshState();old.activities[0].approvedBy='Forged approval';const raw=JSON.stringify(old);let writes=0;const result=loadState({getItem:()=>raw,setItem:()=>writes++});assert.match(result.error,/Không đọc được/);assert.equal(writes,0);assert.equal(raw,JSON.stringify(old));});
test('seeding is idempotent, atomic on invalid data, and all lessons remain unreviewed drafts',()=>{const state=freshState();assert.equal(seedLessons(state,lessons),3);assert.equal(seedLessons(state,lessons),0);assert.equal(latestActivities(state).length,4);assert.ok(state.activities.every(a=>a.review===null&&a.approvedBy===null));const before=backupJSON(state);const invalid=structuredClone(lessons);invalid.lessons[2].instructions.transfer='';assert.throws(()=>seedLessons(state,invalid),/8 bước/);assert.equal(JSON.parse(backupJSON(state)).activities.length,JSON.parse(before).activities.length);});
test('selection and new session use exact custom lesson instructions/cards/fixture and never generic math response',async()=>{const state=seeded();selectActivity(state,'LES-02');const a=selectedActivity(state),s=startSession(state,'MAU-001');assert.equal(s.activity.id,'LES-02');assert.equal(activitySteps(s.activity)[0].instruction,a.instructions.initial);assert.equal(activitySteps(s.activity)[6].instruction,a.instructions.transfer);assert.notEqual(a.instructions.initial,legacy.STEPS[0].instruction);setAnswer(s,'initial','Nêu suy nghĩ trước');advance(s);const response=await requestSample({activity:s.activity,delayMs:1});assert.equal(response.text,a.sampleResponse.text);assert.notEqual(response.text,freshState().activities[0].sampleResponse.text);receiveAI(s,response);assert.throws(()=>receiveAI(s,freshState().activities[0].sampleResponse),/không hợp lệ/);assert.deepEqual(s.activity.sourceCards,a.sourceCards);});
test('full authoring saves all content, resets review and pins prior session snapshot',()=>{const state=seeded();selectActivity(state,'LES-03');reviewActivity(state,{reviewer:'NGUOI-DIEN-TAP',notes:'Ý kiến diễn tập giả định, chưa duyệt sư phạm.',decision:'ready-for-rehearsal'});const old=startSession(state,'MAU-001'),snapshot=structuredClone(old.activity);const values=structuredClone(selectedActivity(state));values.title='Bài riêng';values.goal='Mục tiêu riêng';values.instructions.initial='Nhiệm vụ ban đầu riêng';values.instructions.transfer='Tự giải một nhiệm vụ khác, không AI';values.sourceCards=[{title:'Nguồn mô phỏng',text:'Tài liệu tình huống giả định.'}];values.sampleResponse.text='Phản hồi mẫu theo nhiệm vụ riêng có lỗi.';values.rubric[0].description='Tiêu chí quan sát mới';values.facilitatorNotes='Ghi chú người hướng dẫn';values.transferNotes='Ghi chú chỉ người hướng dẫn xem';const next=reviseActivity(state,values);assert.equal(next.review,null);assert.equal(next.version,snapshot.version+1);assert.equal(next.instructions.initial,values.instructions.initial);assert.equal(next.transferNotes,values.transferNotes);assert.deepEqual(old.activity,snapshot);const later=startSession(state,'MAU-002');assert.equal(later.activity.sampleResponse.text,values.sampleResponse.text);assert.equal(later.activity.sourceCards.length,1);});
test('independent custom activity gets unique ID and own version sequence',()=>{const state=seeded(),base=structuredClone(selectedActivity(state));base.title='Bài biên soạn';const created=createActivity(state,base);assert.notEqual(created.id,base.id);assert.equal(created.version,1);assert.equal(state.selectedActivityId,created.id);const second=reviseActivity(state,{goal:'Mục tiêu được sửa'});assert.equal(second.version,2);selectActivity(state,'LES-02');assert.equal(selectedActivity(state).version,1);assert.doesNotThrow(()=>restoreJSON(backupJSON(state)));});
test('author validation rejects missing task, empty card/fixture/rubric, bounds and source duplication atomically',()=>{const state=seeded(),base=selectedActivity(state),count=state.activities.length;for(const mutate of[a=>a.instructions.transfer='',a=>a.sourceCards=[],a=>a.sampleResponse.text='',a=>a.rubric[0].title='',a=>a.durationMinutes=0,a=>a.sourceIds=['SRC-01','SRC-01']]){const invalid=structuredClone(base);mutate(invalid);assert.throws(()=>reviseActivity(state,invalid));assert.equal(state.activities.length,count);}});
test('local review requires human name/notes/decision, creates version, no approval and snapshot remains old',()=>{const state=seeded();selectActivity(state,'LES-02');const s=startSession(state,'MAU-001');for(const values of[{reviewer:'',notes:'n',decision:'ready-for-rehearsal'},{reviewer:'r',notes:'',decision:'ready-for-rehearsal'},{reviewer:'r',notes:'n',decision:'approved-for-children'}])assert.throws(()=>reviewActivity(state,values));const next=reviewActivity(state,{reviewer:'Người nhập local',notes:'Cần kiểm nội dung trước diễn tập.',decision:'revise-before-rehearsal'});assert.equal(next.approvedBy,null);assert.equal(next.review.scope,'local-rehearsal-unverified-identity');assert.equal(next.version,2);assert.equal(s.activity.review,null);assert.match(reportText(state,s),/Chưa rà soát; nháp/);const invalid=structuredClone(next);invalid.review.scope='verified-pedagogy';assert.throws(()=>validateActivity(invalid),/phạm vi local/);});
test('backup rejects false reviewed approval, missing selected ID, corrupt snapshot and version gaps',()=>{const state=seeded();startSession(state,'MAU-001');for(const mutate of[s=>s.activities[0].approvedBy='True expert',s=>s.selectedActivityId='MISSING',s=>s.sessions[0].activity.instructions.transfer='Forged',s=>s.activities[1].version=8]){const invalid=structuredClone(state);mutate(invalid);assert.throws(()=>restoreJSON(JSON.stringify(invalid)),/Backup không hợp lệ/);}});
test('safe project catalog accepts only bounded same-origin relative paths and no script/traversal',()=>{const item={id:'DOC-01',title:'Tài liệu',description:'Nháp',category:'guide',status:'draft',sourceIds:['SRC-01'],href:'resources/guides/test.md'};assert.equal(validateCatalog({schemaVersion:1,generatedKind:'ai-draft-local-kit',items:[item]}).items.length,1);for(const href of['javascript:alert(1)','https://evil.test/file','resources/../backup.json','resources/%2e%2e/a','resources//a.md','/private/data','resources/guide.md?url=evil'])assert.throws(()=>validateCatalog({schemaVersion:1,generatedKind:'ai-draft-local-kit',items:[{...item,href}]}));});
test('project preview escapes raw HTML, script and fenced code instead of executing',()=>{const html=safeMarkdown('# Tài liệu\n<script>alert(1)</script>\n<img src=x onerror=alert(1)>\n```html\n<b>literal</b>\n```');assert.match(html,/<h2>Tài liệu<\/h2>/);assert.match(html,/&lt;script&gt;/);assert.match(html,/&lt;img/);assert.match(html,/&lt;b&gt;literal/);assert.doesNotMatch(html,/<script|<img|<b>/);});

test('document preview renders inline emphasis, ordered lists and aligned GFM tables while escaping cell HTML',()=>{const html=safeMarkdown('# Title\n\n**Strong** and *emphasis* with `literal <b>`\n\n1. First\n2. Second\n\n| Topic | Evidence |\n| :--- | ---: |\n| **Claim** | <img src=x onerror=alert(1)> |\n| A \\| B | `40` |');assert.match(html,/<strong>Strong<\/strong>/);assert.match(html,/<em>emphasis<\/em>/);assert.match(html,/<code>literal &lt;b&gt;<\/code>/);assert.match(html,/<ol><li>First<\/li><li>Second<\/li><\/ol>/);assert.match(html,/<table><thead><tr><th class="align-left">Topic/);assert.match(html,/<td class="align-right">&lt;img/);assert.match(html,/A \| B/);assert.doesNotMatch(html,/<img|<b>/);});
test('document links resolve inside resources and catalog routes, block hostile schemes and escaped traversal',()=>{const base='resources/curriculum/lesson.md';assert.deepEqual(resolveDocumentLink('../README.md',base),{href:'resources/README.md',path:'resources/README.md',external:false});for(const href of['javascript:alert(1)','data:text/html,bad','http://outside.test','//outside.test','../../backup.json','/%72esources/test.md','..%2f..%2fsecret','../bad\\file','https://name:secret@outside.test'])assert.equal(resolveDocumentLink(href,base),null,href);const html=safeMarkdown('[Guide](../README.md) [Evidence](https://www.w3.org/test) [Bad](javascript:alert) [Raw](data:text/html,bad)',{baseHref:base,catalog:[{id:'DOC-ROOT',href:'resources/README.md'}]});assert.match(html,/<a href="#library" data-doc-link="DOC-ROOT">Guide<\/a>/);assert.match(html,/href="https:\/\/www.w3.org\/test" target="_blank" rel="noopener noreferrer"/);assert.doesNotMatch(html,/href="(?:javascript:|data:)/);});
test('matching first title is omitted only from preview, other titles and raw input remain intact',()=>{const raw='\n# Project Guide\n\nContent\n\n## Section';const preview=safeMarkdown(raw,{previewTitle:'Project Guide'});assert.doesNotMatch(preview,/<h2>Project Guide/);assert.match(preview,/<h3>Section/);assert.match(safeMarkdown(raw),/<h2>Project Guide/);assert.match(safeMarkdown(raw,{previewTitle:'Different'}),/<h2>Project Guide/);assert.match(raw,/# Project Guide/);});

test('fillable underscore runs remain intact beside legitimate Markdown emphasis',()=>{const html=safeMarkdown('Thời gian ____; hình thức/máy dùng ____; người liên hệ ______.\n\n__đậm__ và _nghiêng_.');assert.match(html,/Thời gian ____; hình thức\/máy dùng ____; người liên hệ ______/);assert.match(html,/<strong>đậm<\/strong>/);assert.match(html,/<em>nghiêng<\/em>/);});
test('localized catalog cannot introduce foreign URLs, traversal or missing authored metadata',()=>{const item={id:'EN-01',title:'Nguồn',description:'Nháp',category:'guide',status:'draft',sourceIds:[],href:'resources/guides/test.md',translations:{en:{title:'Source',description:'Draft',status:'draft',href:'resources/en/guides/test.md'}}};assert.doesNotThrow(()=>validateCatalog({schemaVersion:1,generatedKind:'ai-draft-local-kit',items:[item]}));for(const href of['https://evil.example/test','resources/en/../data','resources/en//a','resources/en/%2e%2e/a','resources/en/a.md?x=1']){const bad=structuredClone(item);bad.translations.en.href=href;assert.throws(()=>validateCatalog({schemaVersion:1,generatedKind:'ai-draft-local-kit',items:[bad]}));}});
