import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {validateReferenceCatalog,filterReferences,countryKey,themeKey,reportLink,referenceHash,renderReferences,fetchReferenceCatalog,REFERENCE_IDS,SOURCE_SHA} from '../references-client.js';
import {parseRoute} from '../handoff.js';
const data=JSON.parse(fs.readFileSync(new URL('../references/catalog.json',import.meta.url)));const copy=()=>structuredClone(data);
test('native reference routes preserve explicit locale and bounded source ID without changing library routes',()=>{assert.deepEqual(parseRoute(referenceHash('R03-01','en')),{view:'references',doc:'R03-01',lesson:null,lang:'en',error:null});for(const hash of ['#references?doc=../private','#references?doc=R03-01&doc=R03-02','#references?lesson=LES-02','#references?lang=fr'])assert.ok(parseRoute(hash).error);assert.equal(parseRoute('#library?doc=MAT-04&lang=vi').view,'library');});
test('14 documents retain92 separately owned claim references and57 R03 claims; approvals cannot be forged',()=>{assert.equal(validateReferenceCatalog(data),data);assert.equal(data.cards.length,14);assert.equal(data.meta.r03Claims,57);assert.equal(data.sourceHTMLSha256,SOURCE_SHA);assert.equal(new Set(data.cards.flatMap(s=>s.provenance.claimIDs)).size,92);for(const mutate of [d=>d.cards[0].implication.status='EDUCATION_APPROVED',d=>d.documents=15,d=>d.sourceHTMLSha256='0'.repeat(64),d=>d.cards[0].provenance.claimIDs[0]=d.cards[1].provenance.claimIDs[0],d=>d.cards[0].findings[0].claimIDs=['unknown'],d=>d.cards[0].url='javascript:alert(1)',d=>d.cards[0].title.en='',d=>d.cards[0].countries=['invented']]){const bad=copy();mutate(bad);assert.throws(()=>validateReferenceCatalog(bad));}});
test('canonical country aliases combine historical and newer Canada/Viet Nam documents independently from themes',()=>{assert.equal(countryKey('Canada'),'CA');assert.equal(countryKey('Viet Nam'),'VN');assert.deepEqual(filterReferences(data.cards,{country:'CA'}).map(c=>c.id),['R02-06','R03-02']);assert.deepEqual(filterReferences(data.cards,{country:'VN'}).map(c=>c.id),['R03-01','R03-06','R03-07']);assert.equal(themeKey(data.cards.find(c=>c.id==='R03-06')),'policy');assert.equal(filterReferences(data.cards,{country:'VN',theme:'learning'})[0].id,'R03-01');});
test('search uses both authored languages, supports accents and composes with type/theme/country without mutation',()=>{const before=JSON.stringify(data);assert.ok(filterReferences(data.cards,{query:'schoolwork'}).length);assert.deepEqual(filterReferences(data.cards,{query:'R03-04-C04'}).map(c=>c.id),['R03-04']);assert.deepEqual(filterReferences(data.cards,{query:'R03-01-C03'}).map(c=>c.id),['R03-01']);for(const card of data.cards)for(const id of card.provenance.claimIDs)assert.ok(filterReferences(data.cards,{query:id}).some(c=>c.id===card.id));assert.ok(filterReferences(data.cards,{query:'Việt Nam'}).length);assert.ok(filterReferences(data.cards,{query:'Viet Nam'}).length);assert.equal(filterReferences(data.cards,{query:'impossible-synthetic-query'}).length,0);assert.equal(filterReferences(data.cards,{country:'CA',type:'survey'}).length,0);assert.equal(JSON.stringify(data),before);});
test('bilingual ledger preserves schoolwork n665 for BOTH findings, all source IDs, limits and explicit AI proposals',()=>{for(const locale of ['vi','en']){const html=renderReferences(locale,data,{},'R02-03');for(const id of REFERENCE_IDS)assert.ok(html.includes(`id="reference-${id}"`));assert.ok(html.includes('n = 665'));assert.ok(html.includes('63%'));assert.ok(html.includes('66%'));assert.ok(html.includes(locale==='en'?'AI proposal':'đề xuất AI'));assert.ok(html.includes(locale==='en'?'Limits of application':'Giới hạn áp dụng'));assert.equal((html.match(/<option value="CA"/g)||[]).length,1);assert.equal((html.match(/<details open>/g)||[]).length,1);}const fallback=renderReferences('en',data,{},'R02-06');assert.ok(fallback.includes('Not established in the curated metadata.'));});
test('exact dossier links pin language and source hash and reject unknown IDs/schemes',()=>{assert.equal(reportLink('en','R03-01'),'references/report.html?lang=en#source-R03-01');assert.equal(reportLink('vi'),'references/report.html?lang=vi');assert.throws(()=>reportLink('en','R03-99'));assert.throws(()=>reportLink('fr'));});
test('reference fetch handles unavailable, oversized and invalid catalogs atomically',async()=>{assert.equal((await fetchReferenceCatalog(async()=>({ok:true,text:async()=>JSON.stringify(data)}))).documents,14);await assert.rejects(()=>fetchReferenceCatalog(async()=>({ok:false})));await assert.rejects(()=>fetchReferenceCatalog(async()=>({ok:true,text:async()=>'{bad'})));await assert.rejects(()=>fetchReferenceCatalog(async()=>({ok:true,text:async()=>' '.repeat(500001)})));});
test('render escapes authored metadata while links remain validated and empty state is bilingual',()=>{const malicious=copy();malicious.cards[0].title.en='<img onerror=alert(1)>';const html=renderReferences('en',malicious);assert.ok(html.includes('&lt;img onerror=alert(1)&gt;'));assert.ok(!html.includes('<img onerror'));assert.ok(renderReferences('en',data,{query:'impossible-synthetic-query'}).includes('No matching source'));assert.ok(renderReferences('vi',data,{query:'impossible-synthetic-query'}).includes('Không có nguồn phù hợp'));});
test('actual hosted bootstrap opens only known source, initializes EN and resynchronizes back link on VI toggle',async()=>{
 const {default:vm}=await import('node:vm');const html=fs.readFileSync(new URL('../references/report.html',import.meta.url),'utf8');const script=html.match(/<!-- R04:host-bootstrap -->\s*<script>([\s\S]*?)<\/script>/)[1];
 const make=hash=>{const nodes={'reference-return':{},'reference-host-note':{},'reference-link-status':{},'source-R03-01':{open:false,scrollIntoView(){this.scrolled=true;}}},buttons=[{addEventListener(_,f){this.fn=f;}}];const context={lang:'vi',COPY:{vi:{},en:{}},cards:data.cards,render(){},location:{href:'https://example.test/references/report.html?lang=en'+hash,search:'?lang=en',hash},history:{replaceState(_,__,url){context.replaced=url;}},document:{getElementById:id=>nodes[id],querySelectorAll:()=>buttons},window:{addEventListener(type,f){if(type==='hashchange')context.hashChange=f;}},requestAnimationFrame:f=>f(),URL,URLSearchParams};vm.createContext(context);vm.runInContext(script,context);return{context,nodes,buttons};};
 const {context,nodes,buttons}=make('#source-R03-01');assert.equal(context.lang,'en');assert.equal(nodes['reference-return'].href,'../#references?lang=en');assert.equal(nodes['source-R03-01'].open,true);assert.equal(nodes['source-R03-01'].scrolled,true);assert.ok(context.replaced.endsWith('?lang=en#source-R03-01'));context.lang='vi';buttons[0].fn();assert.equal(nodes['reference-return'].href,'../#references?lang=vi');assert.ok(context.replaced.includes('lang=vi'));const unknown=make('#source-PRIVATE');assert.equal(unknown.nodes['source-R03-01'].open,false);assert.ok(unknown.nodes['reference-link-status'].textContent.includes('Unknown source'));
});

test('actual filter binding preserves editing nodes throughout sequential typing, selection and reset',async()=>{
 const {default:vm}=await import('node:vm');const {renderReferenceLedger}=await import('../references-client.js');const source=fs.readFileSync(new URL('../main.js',import.meta.url),'utf8');const fn=source.match(/function bindReferences\(\)\{[\s\S]*?\n\}/)[0];
 const node=()=>({value:'',events:{},addEventListener(type,fn){this.events[type]=fn;},focus(){this.focused=true;}}),controls=Object.fromEntries(['filters','query','type','theme','country','reset'].map(key=>['reference-'+key,node()])),ledger=node();let writes=0;Object.defineProperty(ledger,'innerHTML',{set(value){writes++;this.content=value;},get(){return this.content;}});
 const context={locale:'en',referenceCatalog:data,referenceFilters:{query:'',type:'',theme:'',country:''},referenceSelected:'R03-01',referenceStatus:'',main:{querySelector:()=>ledger},$:id=>controls[id],renderReferenceLedger,render(){throw Error('A filter action must not replace the full page');},loadReferences(){}};vm.createContext(context);vm.runInContext(fn+';bindReferences();',context);
 const input=controls['reference-query'];for(const char of 'R03-04-C04'){input.value+=char;input.events.input({target:input});assert.equal(controls['reference-query'],input);}assert.equal(context.referenceFilters.query,'R03-04-C04');assert.ok(ledger.content.includes('id="reference-R03-04"'));assert.ok(!ledger.content.includes('id="reference-R03-01"'));assert.equal(writes,10);
 controls['reference-country'].value='CA';controls['reference-country'].events.change({target:controls['reference-country']});assert.ok(ledger.content.includes('No matching source'));controls['reference-reset'].events.click();assert.equal(input.value,'');assert.equal(input.focused,true);assert.equal(controls['reference-country'].value,'');assert.ok(ledger.content.includes('14 matching documents'));assert.equal(controls['reference-query'],input);
});

test('hosted source alignment is bounded after layout/load/fonts and ordinary TOC hashes clear source warnings',async()=>{
 const {default:vm}=await import('node:vm');const html=fs.readFileSync(new URL('../references/report.html',import.meta.url),'utf8');const script=html.match(/<!-- R04:host-bootstrap -->\s*<script>([\s\S]*?)<\/script>/)[1];let fontReady;const fonts=new Promise(resolve=>{fontReady=resolve;}),queue=[],events={},status={textContent:''},node={open:false,alignments:0,scrollIntoView(){this.alignments++;}};const nodes={'reference-return':{},'reference-host-note':{},'reference-link-status':status,'source-R03-04':node};
 const context={lang:'vi',COPY:{vi:{},en:{}},cards:data.cards,render(){},location:{href:'https://example.test/references/report.html?lang=en#source-R03-04',search:'?lang=en',hash:'#source-R03-04'},history:{replaceState(){}},document:{readyState:'loading',fonts:{ready:fonts},getElementById:id=>nodes[id],querySelectorAll:()=>[]},window:{addEventListener(type,fn){events[type]=fn;}},requestAnimationFrame:fn=>queue.push(fn),URL,URLSearchParams};vm.createContext(context);vm.runInContext(script,context);assert.equal(node.open,true);assert.equal(node.alignments,1);
 const flush=()=>{let callbacks=0;while(queue.length){assert.ok(++callbacks<20,'No unbounded animation loop');queue.shift()();}};flush();assert.equal(node.alignments,2);events.load();flush();assert.equal(node.alignments,3);fontReady();await Promise.resolve();flush();assert.equal(node.alignments,4);
 context.location.hash='#source-UNKNOWN';events.hashchange();assert.ok(status.textContent.includes('Unknown source'));context.location.hash='#path';events.hashchange();assert.equal(status.textContent,'');context.location.hash='#methods';events.hashchange();assert.equal(status.textContent,'');assert.equal(node.alignments,4);
 context.location.hash='#source-R03-04';events.hashchange();assert.equal(node.alignments,5);context.location.hash='#path';events.hashchange();flush();assert.equal(node.alignments,5,'A pending source alignment cannot override later TOC navigation');
 context.location.hash='#source-R03-04';events.pageshow();flush();assert.ok(node.alignments>=7,'Restored pages receive a bounded late alignment');
});

test('native selected-source permalink aligns after route reset and rejects unknown or superseded navigation',async()=>{
 const {default:vm}=await import('node:vm');const source=fs.readFileSync(new URL('../main.js',import.meta.url),'utf8');const fn=source.match(/function scheduleReferenceAlignment\(\)\{[\s\S]*?\n\}/)[0];const queue=[];let scrolled=0,view='references';const location={hash:'#references?doc=R03-01&lang=en'};const route=()=>({doc:location.hash.includes('R03-01')?'R03-01':location.hash.includes('R03-04')?'R03-04':null,error:null});const context={referenceAlignmentTicket:0,referenceSelected:'R03-01',referenceCatalog:data,REFERENCE_IDS,referenceFilters:{query:'',type:'',theme:'',country:''},location,parseRoute:route,parseReferenceRoute:route,currentView:()=>view,$:id=>id==='reference-R03-01'?{scrollIntoView(){scrolled++;}}:null,requestAnimationFrame:fn=>queue.push(fn),document:{readyState:'complete'},window:{addEventListener(){}}};vm.createContext(context);vm.runInContext(fn+';scheduleReferenceAlignment();',context);assert.equal(scrolled,0,'Alignment is deferred beyond the route scroll reset');const flush=()=>{let callbacks=0;while(queue.length){assert.ok(++callbacks<20);queue.shift()();}};flush();assert.equal(scrolled,1);
 context.referenceSelected='UNKNOWN';vm.runInContext('scheduleReferenceAlignment()',context);flush();assert.equal(scrolled,1);
 context.referenceSelected='R03-01';vm.runInContext('scheduleReferenceAlignment()',context);context.referenceFilters.query='parent';flush();assert.equal(scrolled,1,'Later typing cancels the pending alignment');context.referenceFilters.query='';vm.runInContext('scheduleReferenceAlignment()',context);view='group';flush();assert.equal(scrolled,1,'Later route navigation cancels alignment');view='references';vm.runInContext('scheduleReferenceAlignment()',context);location.hash='#references?doc=R03-04&lang=en';flush();assert.equal(scrolled,1,'A superseded source permalink cannot scroll the old entry');
});
