import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {ROOM_ROUTES,roomOpening,roomArt,readinessLedger} from '../room-ui.js';
import {renderGuide,renderReview,freshReview,REVIEW_FIELDS,COPY} from '../handoff.js';
import {STEPS,freshState,startSession,activeSession,activitySteps,canAdvance} from '../model.js';
const E=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
test('all eight room paths use local decorative artwork and reject arbitrary asset paths',()=>{assert.equal(ROOM_ROUTES.length,8);for(const route of ROOM_ROUTES){const html=roomOpening(route,'title','context');assert.ok(html.includes(`assets/rooms/${route}.svg`));assert.ok(html.includes('alt=""'));assert.ok(html.includes('aria-hidden="true"'));}for(const route of ['../raw','overview','https://example.test'])assert.throws(()=>roomArt(route));});
test('readiness ledger renders exact self-reported evidence safely, missing owners honestly, without deriving approval',()=>{const keys=['first','second'],records=[{key:'first',status:'in-progress',owner:'A <script>',version:'v2',note:'Original lời ghi\n<iframe>'}],before=structuredClone(records),labels={first:['Một','One'],second:['Hai','Two']};const html=readinessLedger(keys,records,{labels,status:s=>s,locale:'en'});assert.match(html,/A &lt;script&gt;/);assert.match(html,/Original lời ghi\n&lt;iframe&gt;/);assert.match(html,/No owner or rationale recorded/);assert.match(html,/in-progress/);assert.ok(!html.includes('evidence-recorded'));assert.equal((html.match(/data-condition=/g)||[]).length,2);assert.deepEqual(records,before);});
test('correspondence grouping preserves all six exact entered fields and export selectors in both languages',()=>{const review=freshReview();REVIEW_FIELDS.forEach(key=>review[key]=`Original ${key} · Tiếng Việt <script>`);for(const locale of ['vi','en']){const html=renderReview(locale,review);assert.equal((html.match(/class="letter-section/g)||[]).length,3);for(const key of REVIEW_FIELDS){assert.ok(html.includes(`id="feedback-${key}"`));assert.ok(html.includes(E(review[key])));}assert.ok(html.includes('id="export-review-md"'));assert.ok(html.includes('id="export-review-json"'));assert.ok(html.includes(COPY[locale].reviewExportNote));assert.ok(!html.includes('<script>'));}});
test('seven-stop reading map keeps the exact authored documents, explicit language and LES02 destination',()=>{for(const locale of ['vi','en']){const html=renderGuide(locale);assert.equal((html.match(/class="map-stop"/g)||[]).length,7);for(const [id] of COPY[locale].route)assert.ok(html.includes(`#library?doc=${id}&lang=${locale}`));assert.ok(html.includes(`#group?lesson=LES-02&lang=${locale}`));}});
// Exercise the actual session renderer with DOM-free dependencies. Sentinels detect hidden
// content leaks after spatial changes without duplicating the renderer implementation.
const source=fs.readFileSync(new URL('../main.js',import.meta.url),'utf8');
const sessionSource=source.slice(source.indexOf('function renderSession(){'),source.indexOf('function renderReports(){'));
function sessionHTML(state,learnerPreview=false){const deps={roomArt,activeSession,displaySession:s=>s,state,learnerPreview,pageHeader:()=>'<header>Room</header>',previewTools:()=>'',fallbackNotice:()=>'',escape:E,activitySteps,stepTitle:s=>s.title,STEPS,busy:false,badge:E,statuses:{active:'Active',paused:'Paused',completed:'Completed'},sourcePanel:()=>'<aside>SECRET_SOURCE</aside>',reviewFields:()=>'<div>SECRET_FACILITATOR</div>',answerHistory:()=>'<div>SECRET_HISTORY</div>',sessionSelector:()=>'',canAdvance,ui:E,locale:'en'};return Function(...Object.keys(deps),sessionSource+';return renderSession();')(...Object.values(deps));}
test('actual constellation renderer keeps independent work free of source, AI, history and facilitator contents',()=>{const state=freshState();startSession(state,state.learners[0].id);const s=activeSession(state);s.step=6;s.aiResponse={text:'SECRET_AI',provider:'fixture',provenance:'fixture'};s.answers.transfer='Original independent work';const html=sessionHTML(state);assert.match(html,/Original independent work/);for(const secret of ['SECRET_SOURCE','SECRET_AI','SECRET_HISTORY','SECRET_FACILITATOR'])assert.ok(!html.includes(secret),secret);assert.equal((html.match(/class="step-number"/g)||[]).length,8);assert.ok(html.includes('aria-current="step"'));s.step=3;assert.ok(sessionHTML(state).includes('SECRET_SOURCE'));s.step=7;assert.ok(!sessionHTML(state,true).includes('SECRET_FACILITATOR'));});
